### ISSUE TITLE
Error Loading module

### ISSUE THREAD

**Issue by achang28** [oblador/react-native-collapsible#1]
Upgrading from React Native 0.5.0 to 0.7.1 led to this module not being recognized. With 0.5.0, using ```require("Accordion")``` worked just fine.  The module couldn't be recognized after upgrading to 0.7.1, and the command ```require("react-native-collapsible/Accordion")``` also didn't work.

I have also restarted Xcode, the terminal, and Chrome   Ive also restarted my laptop 2x just to be sure.

I was able to solve a similar problem with ```react-native-vector-icons```.  As I was originally using its ```FontAwesome``` module, I only needed to use ```require("FontAwesome")``` in 0.5.0; but using ```require("react-native-vector-icons/FontAwesome")``` fixed the problem with 0.7.1.
![collapsible](https://cloud.githubusercontent.com/assets/3760499/8664283/e18ac7aa-2989-11e5-9a2a-52b1ef070a61.png)

**Comment by oblador** [comment]
This is due to how packager finds dependencies in RN 0.7+. Fixed so that you now can use `require("react-native-collapsible/Accordion")` in [0.2.1](https://github.com/oblador/react-native-collapsible/releases/tag/v0.2.1).
