### ISSUE TITLE
issues with listview

### ISSUE THREAD

**Issue by manask88** [oblador/react-native-collapsible#10]
I wanted to use this component as part of a listview's row.
I had an issue when collapsing or expanding: the collapsible component simply doesnt get updated for some reason. Is there any solution for this?

**Comment by oblador** [comment]
Put your cell rendering in a separate component with it's own state.

**Comment by manask88** [comment]
Thanks @oblador , if you don't mind, can you explain why your suggestion works?

**Comment by oblador** [comment]
It's probably easier if you post the relevant parts your code. :-)

**Comment by manask88** [comment]
this is how it was before:
```javascript
  _renderRow(rowData, sectionID, rowID){
    return (
      <View>
        <TouchableWithoutFeedback onPress={() => {
            if (this.state.isCollapsed) {
              this.setState({isCollapsed: false})
            } else {
              this.setState({isCollapsed: true})
            }
            
          }} >
          <Text >Click to Expand</Text>
        </TouchableWithoutFeedback>
        <Collapsible collapsed={this.state.isCollapsed}>
          <Text >Content</Text>
        </Collapsible>
      </View>
    )
  }
```

**Comment by manask88** [comment]
this is after your suggestion

**Comment by oblador** [comment]
```js
var Cell = React.createClass({
  render(){
    var { isCollapsed } = this.state;
    var { rowData } = this.props;
    return (
      <View>
        <TouchableWithoutFeedback onPress={() => this.setState({isCollapsed: !isCollapsed})}>
          <Text>Click to Expand</Text>
        </TouchableWithoutFeedback>
        <Collapsible collapsed={isCollapsed}>
          <Text>Content</Text>
        </Collapsible>
      </View>
    );
  }
});

(...)

_renderRow(rowData, sectionID, rowID){
  return (<Cell rowData={rowData} />);
}
```

**Comment by oblador** [comment]
@manask88: does this solve your problem? :-)

**Comment by manask88** [comment]
@oblador oh yeah,, i was able to solve it after your suggestion. I was just wondering why your suggestion works as opposed to having all in the same component. I really appreciate your help!

**Comment by oblador** [comment]
The problem is to properly implement `rowHasChanged` on the dataSource. It can be done, but keeping an isolated state for each cell is much easier.

**Comment by SudoPlz** [comment]
I've lost the past 4 hours trying to deal with that.. I would really love to know how I can properly update my `rowHasChanged`.. What is the matter with that?
