### ISSUE TITLE
Unable to scroll using <ScrollView> inside <Accordion>.

### ISSUE THREAD

**Issue by abdulkhaliquem9** [oblador/react-native-collapsible#106]
I have a lengthy list of radio buttons with yes/no options. But, the problem here is I am unable to scroll down to the list , so, Is there any way that I can insert ScrollView at the begin and end of the list of radio buttons
ScrollView
  Radio/
  Radio /
.
.
.
.
  Radio /
/ScrollView

**Comment by abdulkhaliquem9** [comment]
I wrapped complete radio list rendering component inside ScrollView component of react-native, but it doesn't scrolls.
<ScrollView>
         <RadioGroups fields={data.pastMedicalConditions} callback={this.onFieldChange}></RadioGroups >
</ScrollView>

**Comment by abdulkhaliquem9** [comment]
Solved: Able to scroll inside the accordion after making the height of the wrapper <View> smaller the height of ScrollView.

<View style={{flex:1, height:height *0.6  }}>

         <Text>{'HEADING 1'}</Text>
        <ScrollView style={{ height:height *0.7 }}>
        <Accordion
        style={{borderColor:'gray', borderWidth:2}}
          sections={this.SECTION}
          renderHeader={this.renderHeader}
          renderContent={this.renderContent}
        />
        </ScrollView> 

      </View>

**Comment by saurav-bhagat** [comment]
> Solved: Able to scroll inside the accordion after making the height of the wrapper View smaller than the height of ScrollView.
> 
> `
> 
> <`View style={{flex:1, height:height *0.6 }}>
> 
> ```
>      <Text>{'HEADING 1'}</Text>
>     <ScrollView style={{ height:height *0.7 }}>
>     <Accordion
>     style={{borderColor:'gray', borderWidth:2}}
>       sections={this.SECTION}
>       renderHeader={this.renderHeader}
>       renderContent={this.renderContent}
>     />
>     </ScrollView> 
> 
>   </View>
> ```
> 
> `

What is the height variable here?

**Comment by welsdarte** [comment]
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead. I get this error when I apply your method.
