### ISSUE TITLE
Use useNativeDriver?

### ISSUE THREAD

**Issue by slorber** [oblador/react-native-collapsible#112]
Hi,

I am wondering if this library works fine with "useNativeDriver" or not?

If it "can" work, it would probably be helpful to allow using nativeDrive with a prop attribute in this line:

https://github.com/oblador/react-native-collapsible/blob/master/Collapsible.js#L131

I can submit a PR if this is approved

**Comment by iRoachie** [comment]
I don't see why it can't, @slorber make the PR, and let's test it

**Comment by slorber** [comment]
Hmmm according to the doc the native drive does not work to animate height properties:

http://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated.html

For that it seems we have to use experimental `LayoutAnimation`. I don't really know how to use this yet but it's probably a good idea as collapsible animation is not very fast on slow android devices and does not work at all in debug mode

**Comment by iRoachie** [comment]
@slorber I'm not sure how we would opt in to use an experimental version of `LayoutAnimation`. I'm closing this issue since it's not something we can implement currently.
