### ISSUE TITLE
Misbehaviour while showing dynamic content in the collapsible

### ISSUE THREAD

**Issue by ralcon** [oblador/react-native-collapsible#113]
Hi,

i'm searching for a way, to do collapsibles the right thing!

Heres my example:
[Dynamic content in collapsible](https://github.com/ralcon/dynamic-content-in-collapsible)

Heres my problem:
I would like to display some dynamic content in the collapsible. In this example, there will be some times displayed. Don't worry about the same times. I only would like to show some dynamic content.
First of all, the collapse property is set to false in the initial state of redux, but the collapsible is closed (collapsible=true?!?!).
The second misbehaviour is, when the collapsible is shown (collapse=false) and a timeout is set. Then the collapsible closes itself.

What am i doing wrong???

I would like to display some times in the collapsible, without having this misbehaviour of closing the collapsible itself.

Any suggestions?

**Comment by iRoachie** [comment]
Hey @ralcon could you be a bit clearer? I'm not sure what you're asking exactly

**Comment by ralcon** [comment]
Hi, i got the following problem:
My aim is to display several country times, updated by redux (every second via timeout), see my example. When i open the collapsible the first time, everything works fine and is displayed how it should be. but when i activate the timeout  to render the information, the collapsible callapses itself. the variable to identify, if the collapsible is collapsed, is false all the time (a redux property). why is the collapsible collapse itself?
A little bit clearer?

**Comment by ralcon** [comment]
The target state should be:
- Open callaspsibles
- Press "Start" button
- New times are rendered every second

=> Collapsibles should stay 'open' (collapse={false})!

_within the given example:_
_1. git clone https://github.com/ralcon/dynamic-content-in-collapsible_
_2. cd dynamic-content-in-collapsible_
_3. npm install_
_4. react-native run-ios_

**Comment by dongawli** [comment]
@iRoachie : I am too facing the issue while showing dynamic controls in collapsible. Please see the video - https://hub.mangoapps.com/sf/MTAyNzA3XzEzODIxNzA

**Comment by poicooler** [comment]
Having the same issue. When i update a collapsible that is open, it renders nothing even if the collapsed props is at false.

**Comment by sfratini** [comment]
Maybe related to this I am facing: https://github.com/oblador/react-native-collapsible/issues/137

**Comment by eduardomoroni** [comment]
This solves this issue:
https://github.com/oblador/react-native-collapsible/pull/147

**Comment by iRoachie** [comment]
Just merged #147. Release will be out in a few mins.

**Comment by iRoachie** [comment]
Released in [v0.11.0](https://github.com/oblador/react-native-collapsible/releases/tag/v0.11.0)

**Comment by dansanti** [comment]
Hello! 
this bug is present in current version, pr #147 not merged

**Comment by wmonecke** [comment]
@dansanti I am still seeing issues when children inside `Collapsible` re-render. Did you manage to fix it?

**Comment by dansanti** [comment]
PR #147 fix it

**Comment by wmonecke** [comment]
@dansanti It introduced flickering when my content changes height. Does that happen to you too?
