### ISSUE TITLE
Can we add List Menu (Say different categories) instead of  content ..?

### ISSUE THREAD

**Issue by rohananarse** [oblador/react-native-collapsible#114]
Want to create a shop in which there will be the header of category say 
Tshirts (When i click on it the content should come in list)
1.Mens
2.women
etc etc.

IS it possible to attain list view inside accordion content..?

**Comment by iRoachie** [comment]
@rohananarse Sorry for the late reply. The Collapsible can have any content inside so a list is definitely possible.

**Comment by iRoachie** [comment]
Closing as inactive
