### ISSUE TITLE
Keep collapsible open when clicking on other collapsible

### ISSUE THREAD

**Issue by nevin22** [oblador/react-native-collapsible#116]
is this possible ?

**Comment by nicsud1** [comment]
I'm trying to do something similar as well, but with two nested Accordions. Whenever I tap an element of the inner accordion, it causes whatever the active header in the outer accordion is to collpase, while simultaneously expanding the inner accordion resulting in some strange displays

**Comment by olbor** [comment]
Is it possible to keep opened several collapsibles in one accordion?

**Comment by iRoachie** [comment]
@olbor If you want to keep several of them open then use multiple collapsibles are manage the state yourself. The accordion is designed to only have one section open at a time
