### ISSUE TITLE
How to disable warning for enableEmptySections

### ISSUE THREAD

**Issue by preetampatil3d** [oblador/react-native-collapsible#118]
I am getting warning while loading Accordion. 

![image](https://user-images.githubusercontent.com/21255598/30530815-8a6a61f8-9c67-11e7-8a36-b8014b695400.png)

Using following lib versions:

 react-native-collapsible:^0.9.0
 navbar-native: ^1.6.1
 react: 16.0.0-alpha.12
 expo: ^19.0.0

I am unable to disable it, If anyone know the solution please help.

Thanks in advance.

**Comment by iRoachie** [comment]
Hey @preetampatil3d can you create a small example over at https://snack.expo.io so I can see what code produces the message?

**Comment by iRoachie** [comment]
Closing this as inactive
