### ISSUE TITLE
I can't reload the accordion. How can reload it.

### ISSUE THREAD

**Issue by kiritnim** [oblador/react-native-collapsible#119]

**Comment by iRoachie** [comment]
Could you be a bit clearer by what you mean reload?

**Comment by kiritnim** [comment]
Yes. I want to reload only single cell in it. I have button each of cell and reload particular cell tap on button.

**Comment by iRoachie** [comment]
Still not understanding what you mean by reload

**Comment by kiritnim** [comment]
I have problem : https://github.com/oblador/react-native-collapsible/issues/129

**Comment by iRoachie** [comment]
d. #86

**Comment by Devyadav3001** [comment]
this is work but show red line on refereshing props
