### ISSUE TITLE
How can I make a react native expanding cells scrollview in IOS which like the below example?

### ISSUE THREAD

**Issue by mtzluisalfredo** [oblador/react-native-collapsible#120]
How can I make a react native expanding cells scrollview in IOS which like the below example?

https://www.raywenderlich.com/99087/swift-expanding-cells-ios-collection-views

Would anyone can help me? Thanks.

**Comment by iRoachie** [comment]
@mtzluisalfredo It looks like a cool animation but I'm not sure how you would accomplish that with this library. In the example you listed the animation is one on scroll.
