### ISSUE TITLE
How to know accordion dataProvider got changed?

### ISSUE THREAD

**Issue by vijay-dadhich09** [oblador/react-native-collapsible#121]
Hi, I have multiple tabs and on each tab changing accordion dataProvider. But problem is here, how to close last accordion child when change tabs? In new tab the last child index  remain open in the new tab.

**Comment by iRoachie** [comment]
Something like a close all method?

**Comment by vijay-dadhich09** [comment]
yes, I want to close last opened child when change tabs.

**Comment by vijay-dadhich09** [comment]
I could solved the problem using componentWillReceiveProps lifecycle method. The componentWillReceiveProps method being calls when dataProvider gets change and that time componentWillReceiveProps provides nextProps where I have changed the activeSection state.

componentWillReceiveProps(nextProps) {
    // reset activeSection state when change dataProvider
    if (nextProps.activeSection !== this.state.activeSection) {
      this.setState({ activeSection: nextProps.activeSection });
    }
  }
