### ISSUE TITLE
Not working on react-native 0.49.0

### ISSUE THREAD

**Issue by MaxToyberman** [oblador/react-native-collapsible#122]
![screen shot 2017-10-15 at 5 38 18 pm](https://user-images.githubusercontent.com/11058371/31585742-aeca117e-b1cf-11e7-94f6-90031e1e58ad.png)

**Comment by amos80m** [comment]
I had this problem while using `touchableProps={this}`
Removed it and instead, I added the functions i needed into the constructor and Bind them to `this`

**Comment by iRoachie** [comment]
Hey @MaxToyberman could you create a snack over at http://snack.expo.io? I'm having no problems on 0.48

**Comment by MaxToyberman** [comment]
@iRoachie  i had some other problem in my code, everything is working fine now, closing, thank you
