### ISSUE TITLE
Collapsible: When expand it start since 0 even if collapsedHeight > 0

### ISSUE THREAD

**Issue by kosiakMD** [oblador/react-native-collapsible#125]
Have an issue with Collapsible Component:
My `collapsedHeight = { 25 }`
Collapsing is all right - since 'auto' till 25

## Actual Result

When change `collapsed` from `false` to `true` Animation started rising since 0

## Expected Result

Animated rising since 25 to max, but doesn't.

**Comment by iRoachie** [comment]
Not sure what's happening there in your example.  Here's a demo using:

```js
<Collapsible
  collapsed={this.state.collapsed}
  align="top"
  collapsedHeight={20}>
```

![kapture 2018-04-15 at 13 04 25](https://user-images.githubusercontent.com/5962998/38781040-8df850ba-40ad-11e8-94b6-98d816019212.gif)

**Comment by kosiakMD** [comment]
Thank you, but I can't tell you now the situation - we declined to use it, temprorary at least.
M.b. close the issue.

**Comment by iRoachie** [comment]
Coolie! Sorry about taking so long to respond.

**Comment by zabojad** [comment]
This issue happens only on Android. I'm experiencing the same thing with latest release (1.4.0).

**Comment by sgrontflix** [comment]
I'm on v1.6.2 and I still have this issue on Android.

Even after setting collapsedHeight to a number greater than 0, my component "collapses" for a split second and then expands starting from collapsedHeight.

It's a flickering issue, in other words. The animation abruptly starts from 0 and then quickly corrects to collapsedHeight.

Any updates on this?
