### ISSUE TITLE
Pass 'Sections' to the renderHeader() and renderContent() callbacks

### ISSUE THREAD

**Issue by peacechen** [oblador/react-native-collapsible#126]
It would be convenient to pass the original `sections` array through to the renderHeader() and renderContent() callbacks.  In my use case, multiple sections are generated dynamically, each passed to Accordion instances.  The contents need to reference the complete `sections` array; recreating that within `renderContent` is painful.

I'll create a PR for this.

**Comment by peacechen** [comment]
Created PR #127

**Comment by iRoachie** [comment]
Added in https://github.com/oblador/react-native-collapsible/commit/ecdb10277359e964a693d4228fff59174baa962b. Should be available in next release

**Comment by iRoachie** [comment]
Released in [0.10.0](https://github.com/oblador/react-native-collapsible/releases/tag/0.10.0). Just for owner to push to npm! Thanks again
