### ISSUE TITLE
Black underlay

### ISSUE THREAD

**Issue by Traviskn** [oblador/react-native-collapsible#13]
Thanks for this project, it has been very helpful!

I'm using the accordion component and have noticed that there is a black underlay on the headers when you tap them to open a section.  Is there a way to change the color of the black underlay?

**Comment by oblador** [comment]
Hi @Traviskn,

Just set a `backgroundColor` on your headers (be it `'white'`).

**Comment by oblador** [comment]
This functionality is now available in [0.5.3](https://github.com/oblador/react-native-collapsible/releases/tag/v0.5.3).
