### ISSUE TITLE
Can't be used with any animated components

### ISSUE THREAD

**Issue by jiyarong** [oblador/react-native-collapsible#134]
like react-native-zoom-image 

I put my component in Collapsible, and it will been disappears when my animated components is trigger

**Comment by iRoachie** [comment]
Could you create a small example on https://snack.expo.io that replicates this behaviour?

**Comment by sfratini** [comment]
Maybe related to this: https://github.com/oblador/react-native-collapsible/issues/137

**Comment by jiyarong** [comment]
I fixed it with this code
at Collapsible.js line 157
```
 const { collapsed } = this.props;
    const { height, contentHeight, measuring, measured } = this.state;
    const hasKnownHeight = !measuring && (measured || collapsed);
    const style = hasKnownHeight && {
      overflow: 'scroll',
      height: height,
    };
    const contentStyle = {};
```
 then the problem has been solved

**Comment by iRoachie** [comment]
I'd still really like to see how you are using this in your use case. Can you also create a PR so I can test the changes?

**Comment by NorbertoC** [comment]
I had a problem that the collapsible was being closed and showing no content, and when I tap again the content was shown. I don't know why, but this fix my problem too.

Thanks!

**Comment by iRoachie** [comment]
Closing this as inactive. Releasing a new version today that should deal better with managing the content of views. Would love for you to try it and see if the problem still persists.

**Comment by brycepavey** [comment]
@iRoachie this solution also fixes my use case. here's a gif of whats occurs when using the library as-is. replacing `overflow: 'hidden'` with `overflow: 'scroll'` solves it for me. I think there's potentially more to this though, as this occurs when I'm using tcomb-form-native within the accordion 

![capture](https://user-images.githubusercontent.com/6986339/42425461-4b247358-8361-11e8-8a7e-de6774fdb348.gif)

**Comment by MelYasuda** [comment]
I'm using Accordion with react-native-swipeout and had the same problem where items disappear when I try to swipe to show the hidden button. I tried @brycepavey 's solution and it worked! Thank you for sharing the solution @brycepavey !
