### ISSUE TITLE
How to disable accordion?

### ISSUE THREAD

**Issue by shafips** [oblador/react-native-collapsible#135]
I am using accordion, i just want to disable accordion programatically.

**Comment by iRoachie** [comment]
Added in https://github.com/oblador/react-native-collapsible/pull/136/commits/323c810c999c5d41c72eb6a92745e6c5d649504e. Will be available in next release

**Comment by iRoachie** [comment]
Released in [v0.10.0](https://github.com/oblador/react-native-collapsible/releases/tag/0.10.0). Just waiting for author to publish to version npm.

You can use directly from GitHub in the meanwhile:

In your package.json:
` "react-native-collapsible": "https://github.com/oblador/react-native-collapsible.git"`
