### ISSUE TITLE
How to close accordion?

### ISSUE THREAD

**Issue by Dror-Bar** [oblador/react-native-collapsible#139]
Hey,
I want to close the accordion (all sections) when the user presses on the **content** of one of the sections. How to do this? I think maybe I need to set activeSection to false but I have no idea how to achieve this.

Thanks.

**Comment by iRoachie** [comment]
You can use the `activeSections` prop to manage which sections are open. Here's an example snack I made to show this in action. https://snack.expo.io/rksAS21VG

**Comment by Dror-Bar** [comment]
Thanks.
I was thinking about using state, but wasn't aware of:

onChange={activeSection => this.setState({ activeSection })}
activeSection={this.state.activeSection}

Your example solved my issue.

**Comment by iRoachie** [comment]
Great to have helped!
