### ISSUE TITLE
SwipeableRow in renderHeader

### ISSUE THREAD

**Issue by martinlavanant** [oblador/react-native-collapsible#142]
Hello,

First of all, thanks for the awesome lib!
I ran into a problem using a Swipeable component in the renderHeader method of the Accordion.
I believe the swipe event is taking over the press event and the Accordion is not collapsing.

Sorry to ask this but is there anyway I could get it to work with both events?
Here's a snippet of my code (Hope it's enough)  :
```
 _renderHeader(section, index) {
        return (
            <Animatable.View
                duration={300}
                transition="backgroundColor"
                style={{ backgroundColor: 'rgba(239,239,239,1)'}}>
                <SwipeRow
                    disableRightSwipe={true}
                    rightOpenValue={-100}
                >
                    <TouchableOpacity style={[styles.backRightBtn, styles.backRightBtnRight]}>
                        <Text style={styles.backTextWhite}>SUPPRIMER</Text>
                    </TouchableOpacity>
                    <View>
                        <Text>Test</Text>
                    </View>
                </SwipeRow>
            </Animatable.View>
        );
    }
```

Thanks in advance

**Comment by iRoachie** [comment]
Would allowing the _renderHeader to have an `onPress` param solve your problem? It means you'd have to call this method yourself though.

**Comment by iRoachie** [comment]
Closing as inactive.

**Comment by shihab12** [comment]
Hi There,

I am having the same issue as MartXXIII. My content is not rendering when I am pressing the header. Can anyone help me out with this issue? Here is my renderHeader function:
`  _renderConditionSectionHeader = (section, i, isActive) => {
    return (
      <SwipeRow rightOpenValue={-100} disableRightSwipe={true}>
        <View>
          <Button full danger>
            <Text>Delete</Text>
          </Button>
        </View>
        <View>
          <View>
            <Text
              style={{
                color: 'white',
                // paddingTop: 15,
                fontSize: 15,
                fontWeight: 'bold'
              }}
            >
              {section}
            </Text>
          </View>
          <View
            style={{
              flex: 1,
              flexDirection: 'row',
              alignItems: 'flex-end',
              justifyContent: 'flex-end'
            }}
          >
            {isActive ? (
              <Icon
                name="minus"
                color="white"
                type="light"
                size={16}
                style={{ paddingTop: 2 }}
              />
            ) : (
              <Icon
                name="plus"
                color="white"
                type="light"
                size={16}
                style={{ paddingTop: 2 }}
              />
            )}

            <Button transparent>
              <Icon
                name="trash"
                color="red"
                type="light"
                size={16}
                onPress={() => this._deleteCondition(i)}
                // style={{ paddingTop: 2 }}
              />
            </Button>
          </View>
        </View>
      </SwipeRow>
    );
  };`

and here is my Accordion component:
`                    <Accordion
                      sections={this.state.conditions}
                      activeSections={this.state.activeConditionSections}
                      renderHeader={this._renderConditionSectionHeader}
                      renderContent={this._renderContent}
                      onChange={this._updateConditionSections}
                      sectionContainerStyle={
                        Platform.OS === 'ios'
                          ? accordioStyle.inputIOS
                          : accordioStyle.inputAndroid
                      }
                    />`

Thanks in advance!

**Comment by Jatael** [comment]
Hi,

I have the exact same issue (still trying to find a solution),
@iRoachie when you talk about allowing the _renderHeader to have an onPress param, does this feature already exist or need i to create it? Could be a good way to resolve our issue i think

Thanks a lot for the lib btw :)
