### ISSUE TITLE
Disable section from being expanded

### ISSUE THREAD

**Issue by pkantsedalov** [oblador/react-native-collapsible#148]
@oblador 
Hi guys. 
Thank you for your work.

I have such flow where I need to open the topmost section first, then do some actions there and only after that I have to open the next one (there could be 3 sections).

Just want to ask is it possible somehow to make any of sections disabled?

**Comment by iRoachie** [comment]
Hey man! Can't answer you write now cause I'm at work. Will try to go through the issues and PRs this evening into tonight. Thanks for understanding

**Comment by pkantsedalov** [comment]
@iRoachie Thank you a lot .
Of course take your time!

Here is an example I'm talking about: https://www.npmjs.com/package/react-native-bar-collapsible

**Comment by iRoachie** [comment]
Closing this as inactive. If the above solution didn't work for you then ping me.

**Comment by brenwell** [comment]
Just a suggestions: It would be nice if the row didn't give feedback when it doesn't expand
