### ISSUE TITLE
how to use TouchableHighlight or TouchableOpacity inside renderheader?

### ISSUE THREAD

**Issue by sohanpatil44** [oblador/react-native-collapsible#152]
My renderheader method is like this....

**Comment by sohanpatil44** [comment]
_renderHeader(section, i, isActive) {
    return (
    <View >
      <Animatable.View duration={400} style={[styles.header, isActive ? styles.active : styles.inactive]} transition="backgroundColor">
   <View style={{flexDirection:'row'}}>
   <View>
     <Icon name='keyboard-arrow-up'size={25} color={isActive ?'#214263' : '#16a085'}/>
     <Icon name='keyboard-arrow-down'size={25} color={isActive ?'#1abc9c' : '#214263'}/>
     </View>
       <Text style={styles.headerText}> {section.header}</Text>
    <TouchableOpacity>   <Icon name='edit'size={25} color='skyblue'onPress={this.addInvoice} /></TouchableOpacity>
        <Icon  name='file-upload'size={25} color='red'/>
       <Icon name='delete'size={25} color='red'/>
      </View>
      </Animatable.View>
     
      </View>
    );
  }

**Comment by HamzahNizami** [comment]
You need to change the _renderHeader to the following

_renderHeader = (section, i, isActive) => {...}

**Comment by sohanpatil44** [comment]
yes, i did this and now its working
