### ISSUE TITLE
Identify tapped Index

### ISSUE THREAD

**Issue by nicoaureliovillanueva** [oblador/react-native-collapsible#153]
Hi! can you please give me a example for identifying the tapped index?

Thanks!

**Comment by iRoachie** [comment]
The `onChange` prop passes back the index tapped.

**Comment by iRoachie** [comment]
Closing as inactive

**Comment by ishaqashraf** [comment]
@iRoachie  i want when the user click on accordion header then a loading indicatior appears for 30 sec and then stopeed the indicator and accordion expands.. how to achieve this ?

**Comment by iRoachie** [comment]
You can just put the logic in the onChange callback. onChange is function, so you can do whatever logic you need to do before setting the state
