### ISSUE TITLE
Accordion sticky headers

### ISSUE THREAD

**Issue by JoseVf** [oblador/react-native-collapsible#154]
Is there a way to set the accordion headers sticky?
I'm creating a kind of checklist app with different groups to evaluate composed of different items.
My thinking is that the user might be able to always see on top of the screen the group that is evaluating (make the active header sticky at the top).

Current behavior:
![demonstration](https://user-images.githubusercontent.com/22102736/36487935-23e804fe-16f0-11e8-82ae-37217c131c11.gif)

**Comment by iRoachie** [comment]
react-native-collapsible doesn't support this feature internally, however we can use a combination of collapsible and React Native's SectionList component to get this behavior.

Here's the code and snack so you can see how it works https://snack.expo.io/BJ291g-OM.

![sticky headers](https://user-images.githubusercontent.com/5962998/36650654-f4fb1cce-1a7a-11e8-8038-a8d93daf98ab.gif)

**Comment by JoseVf** [comment]
That's exactly what I was searching. Gonna use that until the component itself allow that behavior.
Thanks a lot!
