### ISSUE TITLE
passing ObservableArray instead of Array to `sections` results in warning

### ISSUE THREAD

**Issue by schumannd** [oblador/react-native-collapsible#157]
If I am not mistaken, `ObservableArray` can be used just like `Array`

I get the following warning:
```Warning: Failed prop type: Invalid prop `sections` of type `object` supplied to `Accordion`, expected `array`.```

**Comment by iRoachie** [comment]
What is ObservableArray?

**Comment by tegarkurniawan** [comment]
@schumannd what is the answer to this problem, this same issue ?

**Comment by iRoachie** [comment]
I’m not sure what is observable array? Is this from knockout?

**Comment by schumannd** [comment]
see #156 
Observable array is from mobx.

The solution was making sure I was passing an array as sections

**Comment by iRoachie** [comment]
@tegarkurniawan mobx docs explain how to use maps and so on with Observable array.

> Due to limitations of native arrays in ES5 observable.array will create a faux-array (array-like object) instead of a real array. In practice, these arrays work just as fine as native arrays and all native methods are supported, including index assignments, up-to and including the length of the array.

> Bear in mind however that Array.isArray(observable([])) will yield false, so whenever you need to pass an observable array to an external library, it is a good idea to create a shallow copy before passing it to other libraries or built-in functions (which is good practice anyway) by using array.slice(). In other words, Array.isArray(observable([]).slice()) will yield true.

https://mobx.js.org/refguide/array.html
