### ISSUE TITLE
refreshing section data give following error

### ISSUE THREAD

**Issue by changulpaye** [oblador/react-native-collapsible#158]
I am trying to implement search functionality for collapsible. But when I search something and refreshing data with setState method it gives me following error.

TypeError: undefined is not a function (evaluating 'this.props.sections.map')

This error is located at:
    in Accordion (at App.js:252)
    in RCTView (at View.js:78)
    in View (at App.js:209)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
render

**Comment by iRoachie** [comment]
Could you create a snack.expo.com? It’s actually pretty hard to tell what’s wrong without seeing your code

**Comment by iRoachie** [comment]
Closing this as inactive. Ping me or create a new issue with a clear example of your usage.
