### ISSUE TITLE
Question regarding performance

### ISSUE THREAD

**Issue by jamesfzhang** [oblador/react-native-collapsible#16]
Say I have a very large ListView and I use this library to collapse all the items in the ListView. Theoretically this should improve the performance significantly since the items in the ListView are hidden and not rendered, is this correct?

The other thing that I noticed is that collapsing a ListView doesn't re-render new items that are now supposed to be pushed up into the view since there is more space. I have to scroll down for new items to render. See screencast:

![screencast](https://cloud.githubusercontent.com/assets/2057670/12376247/aad02824-bc9e-11e5-971c-f0035a376ade.gif)

**Comment by oblador** [comment]
Hi, performance is likely not affected much since the module currently render its content to know the dimensions. Doing so on tap might cause dropping frames, but I can give it a try.

Your ListView bug is a bug with ListView unfortunately, try tweaking the render props.

**Comment by jamesfzhang** [comment]
Ahh I see. I'm looking for any ways to improve performance of large ListViews. I've went over all of the related issues in the RN GitHub as well as using [SGListView](https://github.com/sghiassy/react-native-sglistview), so I was hoping that this library could help :)

Regarding the ListView bug, tweaking the render props didn't help.

**Comment by oblador** [comment]
Yeah, ListView is not perfect... Glad you worked it out! =)
