### ISSUE TITLE
How to use react-native-view-more-text  inside  react-native-collapsible

### ISSUE THREAD

**Issue by emorphisgit** [oblador/react-native-collapsible#160]
I want to use react-native-view-more-text inside react-native-collapsible but it hides contents how I use this with react-native-collapsible.

**Comment by iRoachie** [comment]
Hey @emorphisgit, the collapsible calculates the distance to expand by calculating the height of its children. If you use children that their height change after the collapsible expands then the height will be incorrect. 

Don't think you will be able to use  `react-native-view-more-text` effectively with this library.

**Comment by kishanbharda** [comment]
Any solution for this issue ?
