### ISSUE TITLE
Align content prop not working

### ISSUE THREAD

**Issue by karimkhamwani** [oblador/react-native-collapsible#164]
what i want is collapseview should come from top rather than bottom for eg if you click header view comes in bottom what i want is to generate same view from top rather than bottom help

**Comment by iRoachie** [comment]
I'm not understanding clearly, could you be a little clearer? Use pictures if necessary

**Comment by karimkhamwani** [comment]
![16_search](https://user-images.githubusercontent.com/14240363/38732973-abaf9c82-3f39-11e8-8daa-3b81380f2f82.jpg)
![16_search_advanced](https://user-images.githubusercontent.com/14240363/38732985-b1209630-3f39-11e8-8be3-1972080abac3.jpg)

**Comment by iRoachie** [comment]
Can you make a [snack](https://snack.expo.io) showing the code you used to make this? Kinda hard to debug without seeing an example.

**Comment by iRoachie** [comment]
Closing as inactive.
