### ISSUE TITLE
How put header on Bottom when open the accordion 

### ISSUE THREAD

**Issue by dcoria7** [oblador/react-native-collapsible#165]
When I click on header accordion I would like to see this header on the bottom of all content opened but I don't know if there's a property to do that.
<img width="427" alt="captura de pantalla 2018-04-13 a la s 09 31 38" src="https://user-images.githubusercontent.com/5082455/38740575-8aa04df2-3efd-11e8-8bea-2834780a59c2.png">
<img width="412" alt="captura de pantalla 2018-04-13 a la s 09 31 50" src="https://user-images.githubusercontent.com/5082455/38740576-8ab6318a-3efd-11e8-95ac-ff978f96bd64.png">

**Comment by iRoachie** [comment]
So it should expand upwards instead?

**Comment by dcoria7** [comment]
@iRoachie yes

**Comment by iRoachie** [comment]
Ahh that sounds like a good thing to add.

**Comment by iRoachie** [comment]
Released in [v0.11.0](https://github.com/oblador/react-native-collapsible/releases/tag/v0.11.0)
