### ISSUE TITLE
TS missing prop for Accordion 

### ISSUE THREAD

**Issue by bang88** [oblador/react-native-collapsible#172]
```
- touchableComponent 
- touchableProps
```

missing these props for Accordion Component.

By the way. can not locate 'react-native-collapsible/Accordion' module in VSCode.

**Comment by iRoachie** [comment]
Thanks for reporting, will check it over the weekend

**Comment by iRoachie** [comment]
Fixed in https://github.com/oblador/react-native-collapsible/commit/285c871c226d380cde9baa83bcb708e4f9f7a3ef. Will be available in next release.

**Comment by iRoachie** [comment]
Released in [`0.11.1`](https://github.com/oblador/react-native-collapsible/releases/tag/v0.11.1)
