### ISSUE TITLE
Content is laid out repeatedly during expand animation

### ISSUE THREAD

**Issue by andriichernenko** [oblador/react-native-collapsible#175]
I am trying to use `<Collapsible />` with `<Text />`. Everything works fine except one thing: text layout changes while animation is in progress. 

The result looks pretty janky:
![current](https://user-images.githubusercontent.com/4421971/39196449-703cd276-47e2-11e8-8d9e-2ba3a0db51eb.gif)

The expand animation looks much better if the content is laid out just once:
![improved](https://user-images.githubusercontent.com/4421971/39196547-ad9c4a70-47e2-11e8-94ab-9f974738601c.gif)

**Comment by andriichernenko** [comment]
This issue can easily be fixed by wrapping the children in a `<View />` with fixed height:
```javascript

render() {
    // ...
    return (
      <Animated.View style={style} pointerEvents={collapsed ? 'none' : 'auto'}>

        <Animated.View
          ref={this._handleRef}
          style={[this.props.style, contentStyle]}
          onLayout={this.state.animating ? undefined : this._handleLayoutChange}
        >

          <View style={{ height: measured ? contentHeight : null }} > // <=====

            {this.props.children}

          </View>

        </Animated.View>

      </Animated.View>
    );
  }

```

I can start a PR, but I am not sure this won't break anything. What do you think?

**Comment by iRoachie** [comment]
Awesome man that looks great. Let's try it out. My only concern might be scrollable content inside the collapsible. But the UX has never been great there either. Let's do it! Would appreciate the PR

**Comment by iRoachie** [comment]
https://github.com/oblador/react-native-collapsible/releases/tag/v0.11.3
