### ISSUE TITLE
load more option in accordion 

### ISSUE THREAD

**Issue by ishaqashraf** [oblador/react-native-collapsible#176]
hi, is there any option to paginate list i mean i have 10000 records in my list . so i use pagination from server but i want when the user go to last the new list render in array ? 
like in flatlist there is prop which is onReached . so is there any prop in this library ?

**Comment by iRoachie** [comment]
I'm not understanding you're use case. Accordion is just for toggling displaying of different sections.

**Comment by ishaqashraf** [comment]
so i there any way to use flatlist in accordion component?

**Comment by iRoachie** [comment]
You have to handle the content inside the Accordion yourself. Are you saying you have 10,000 sections?

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by rohitdharavath** [comment]
Is there a way to handle onEndReached something like FlatList prop? If you can add onEndReached, then pagination can be handled by updating the sections data.

**Comment by tiffanym19** [comment]
is there pagination in accordion?

**Comment by vivek-bluebash** [comment]
Yeah, is there a way to paginate the accordion, like onEndReached attribute in the Flatlist ?

**Comment by Tonyibra** [comment]
Found any ?
