### ISSUE TITLE
accordion animation slow

### ISSUE THREAD

**Issue by ishaqashraf** [oblador/react-native-collapsible#177]
its working fine when i have 10 records in my list but when i have 10,00 records in my list its working very slow like when i tap 1 records teh after 5 sec the accordion will open and if i click 2 records at a time then the accordion behaves like mad

**Comment by iRoachie** [comment]
It's a render to the page, so if you have a lot of presentation that blocks the UI thread then it will stutter. It's the same as when using tab navigation and trying to switch to a tab with a long list with lots of data - the effect is the same. You may want to look at optimizing your UI in a different away.

Were you on android by the way? You may want to test it with the debugging mode off

**Comment by ishaqashraf** [comment]
@iRoachie  i tested on it debug and as well as relaese but having issues on long list , can u suggest me a good way to sollve this issue ?

**Comment by iRoachie** [comment]
Is there any reason you can't display the info differently? Why are you trying to displaying 10,000 items? It's not good UX to have very long list. 

You can try using some methods on the FlatList to lower the initial load. Check out:
[`initialNumToRender `](https://facebook.github.io/react-native/docs/flatlist.html#initialnumtorender)

**Comment by ishaqashraf** [comment]
can you please make a example for me in which u can used accordion component with flatlist.. 
i will be thankful to you .
