### ISSUE TITLE
How to toggle Accordion collapsed={} when clicking a header?

### ISSUE THREAD

**Issue by lukamrkonjic** [oblador/react-native-collapsible#179]
Hey guys!

I love this module but we've been having some issues with the Accordion. I try to make it so that when you click a header on an accordion, it expands showing multiple TouchableOpacities(that when clicked depending on which button, adds the header text to the title of the accordion). 

The problem is that when we click on it, it expands, but it does not work to toggle the state isCollapsed within the _renderHeader function because it is "invisible _"? We solved this by binding the state, feels unnecessary complicated. 

This works one by activating the onPress={} of the TouchableOpacity, but does not work again after closing it. 

There has to be a better way of doing this, please help me out if you can! Sorry if my text was not that clear.

Thanks a bunch

**Comment by LukaMrkonjic** [comment]
For reference: I did this after 9 coding hours so my brain messed up haha. I think I just solved this by binding the _-functions instead of state, my bad. But if you want to add something to this, be my guest! 😀

**Comment by iRoachie** [comment]
I think https://github.com/oblador/react-native-collapsible/issues/183#issuecomment-384858331 might be able to help you. Let me know.

**Comment by ishaqashraf** [comment]
there is a function onChange(index)   which willl give you the index . if u click on header (open) it will give you index no. an when u clock accordion it will give you false..

**Comment by LukaMrkonjic** [comment]
Sorry for not answering, and thank you very much for the lovely answers!
