### ISSUE TITLE
[Android] React error when declaring a component as content

### ISSUE THREAD

**Issue by vaporwavie** [oblador/react-native-collapsible#182]
Hey guys! I'm having some trouble declaring a component at the `content`. This is the output I'm having: 

![screenshot_1524789035](https://user-images.githubusercontent.com/11232965/39338458-3e9807fa-4999-11e8-9f7f-39fc0e4ee278.png)

This is my component code (`DashboardComponent.js`):

```javascript
<View>
      <Text>Test</Text>
</View>
```

This is the way I'm declaring the component:

```javascript
const SECTIONS = [
  {
    title: "Dashboard",
    content: <Dashboard />
  }
]
```
My `package.json`
```json
   "react-native": "0.54.1",
    "react-native-collapsible": "^0.10.0",
```

If I remove the `View`, the component loads fine. The problem is that I *need* the `View`. Does this package supports nested views? Is there any workaround for it? Thanks!

**Comment by iRoachie** [comment]
You can control any logic of display in the `renderContent` prop. Here's an example using a component like your example above. https://snack.expo.io/SJW5eXxTG

**Comment by vaporwavie** [comment]
It worked! Thank you very much :smile:
