### ISSUE TITLE
Animated on open but not close

### ISSUE THREAD

**Issue by ggepenyan** [oblador/react-native-collapsible#185]
I'm working in `CRNA`.
I've put `Collapsible` is inside `ScrollView` -> `View`.
`<Collapsible collapsed={isCollapsed}>` - I've used only Collapsible, **haven't used Accordion**.
I got it on both android and ios platforms.
```
"expo": "^25.0.0",
"react": "16.2.0",
"react-native": "0.52.0",
"react-native-collapsible": "0.11.2"
```

**Comment by iRoachie** [comment]
Can you give an example with the content you used inside the collapsible?

**Comment by Gretchin** [comment]
Same with Accordion. Checked on Android only, without expo.
```
"react": "16.3.1",
"react-native": "0.55.3",
"react-native-collapsible": "^0.11.2",
```
My `renderContent` func:
```
renderContent={(section, i, isActive, sections) =>
    <TouchableHighlight underlayColor="white" key={section.news_id} onPress={() => this.onNewsPress(section)}>
        <View style={{ backgroundColor: '#5b8ebe', paddingHorizontal: 16, paddingVertical: 18, elevation: 4, }}>
            <Text style={{ fontSize: 15, color: 'rgba(255, 255, 255, 0.64)' }} >{section.news_short_description}</Text>
        </View>
    </TouchableHighlight>
}
```

**Comment by iRoachie** [comment]
Does the example app in the repo work for you?

**Comment by Gretchin** [comment]
I replaced Accordion on presented below Collapsible and it works good. I don't know.
```
<Collapsible
    collapsed={this.state.isCollapsed}
    style={styles.collapseContainer}
>
    <Text style={styles.description}>{description}</Text>
    <TouchableOpacity
        onPress={onPress}
        style={styles.fullShowContainer}
    >
        <Text style={styles.fullShowText}>{button}</Text>
    </TouchableOpacity>
</Collapsible>
```
P.S.: `Text` from NativeBase here and in the previous comment

**Comment by ggepenyan** [comment]
I will give code example in two three days

**Comment by iRoachie** [comment]
@ggepenyan Did you get through?

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
