### ISSUE TITLE
Is it possible to have more controls inside the content other than default TEXT

### ISSUE THREAD

**Issue by uthaykula** [oblador/react-native-collapsible#186]
Hi 

First of all this is not an issue, just i'm trying to use it for some other purpose....

I have made a component using collapsible Animation and i'm using more than one accordion in one screen by passing content as props and it is working as expected as long as title & content remain string.  I changed the render method to accept any props like this 

ORIGINAL EXAMPLE (Working) 

```
_renderContent(section, i, isActive) {
		return (
			<Animatable.View 
					duration={400}  
					style={[styles.content, isActive ? styles.active : styles.inactive]} 
					transition="backgroundColor">
                                          **<Text>{section.content}</Text>**
		        </Animatable.View>
		);
	} 
```
I changed it as follows

```
_renderContent(section, i, isActive) {
		return (
			<Animatable.View 
					duration={400}  
					style={[styles.content, isActive ? styles.active : styles.inactive]} 
					transition="backgroundColor">
                                        **{section.content}** 
		        </Animatable.View>
		);
	}
```
When i pass any component as props and it is rendering perfectly in DEBUG configuration on simulator and on device but as soon as change the configuration to RELEASE additional component is not rendering other than Text component in the props. I'm not sure what i'm missing for RELEASE configuration. 

Please advise me. 

Thanks.

**Comment by iRoachie** [comment]
You can render anything you like in the `renderContent` method. Here's an example snack where an element is return instead https://snack.expo.io/@roach_iam/accordion-render-element

**Comment by uthaykula** [comment]
Thanks @iRoachie That's worked.
