### ISSUE TITLE
Last item in accordion overlaps with element

### ISSUE THREAD

**Issue by FrancisMurillo** [oblador/react-native-collapsible#188]
Hello,

I found a strange behavior when activating the last item in an accordion, it overlaps with the item below it.

![overlap](https://user-images.githubusercontent.com/7600642/39902207-81d2a306-54ff-11e8-886c-78cbdddcf4f5.png)

Not a big issue since an easy workaround is to add a small `marginTop` to prevent the overlap. I reckon the problem stems from using `position: 'absolute'`.

**Comment by iRoachie** [comment]
This should be fixed by https://github.com/oblador/react-native-collapsible/pull/180. Can you reproduce this on https://snack.expo.io? I'll test it when I merge in the above PR

**Comment by iRoachie** [comment]
Closing as inactive.
