### ISSUE TITLE
Cannot find module 'react-native-collapsible/Accordion'

### ISSUE THREAD

**Issue by jerryheir** [oblador/react-native-collapsible#189]
I try to create a .tsx file to use Accordion, 
`import Accordion from 'react-native-collapsible/Accordion'`
but it tells me **cannot find module 'react-native-collapsible/Accordion'**
Please what am I doing wrong?

**Comment by iRoachie** [comment]
Hey @jerryheir What version are you using?

**Comment by iRoachie** [comment]
Nevermind, I encountered the bug as well, will fix soon.

**Comment by jerryheir** [comment]
Okay, thanks a lot

**Comment by jerryheir** [comment]
"react-native-collapsible": "^0.11.2",

**Comment by iRoachie** [comment]
Fixed in https://github.com/oblador/react-native-collapsible/commit/ba349c6014a395fea276edb350787dea75c6ba3f, will be available next release

**Comment by iRoachie** [comment]
Released in [0.11.3](https://github.com/oblador/react-native-collapsible/releases/tag/v0.11.3)

**Comment by Anujmoglix** [comment]
I am getting same issue in  "react-native-collapsible": "^1.2.1",

**Comment by iRoachie** [comment]
@Anujmoglix please create a new issue.
