### ISSUE TITLE
How to update _renderHeader function

### ISSUE THREAD

**Issue by jerryheir** [oblador/react-native-collapsible#191]
Hello Great Minds, I have an imported component to be returned in my _renderHeader(), and in the component it needs to update an image when a used clicks the Accordion to be expanded using state, but its throwing errors. Please, how can I go about this. So far, I don't the onChange function props can do this for me. And I can't use View event handler like the TouchableOpacity onPress, it throws an error also

**Comment by iRoachie** [comment]
`renderHeader` is a prop that just expects a function that returns a react component. You can put whatever logic in that function. See [this comment](https://github.com/oblador/react-native-collapsible/issues/145#issuecomment-368365486) for an example doing it with state. The example is for `renderContent` but it should be the same for `renderHeader`

**Comment by jerryheir** [comment]
I will try it and see what happens

**Comment by iRoachie** [comment]
Closing as inactive
