### ISSUE TITLE
Feature request: Add chevron change and default style changes when toggled 

### ISSUE THREAD

**Issue by pashute** [oblador/react-native-collapsible#193]
I would like a chevron (a small triangle or any other icon, that toggles state when collapsed or opened. 

Also it would be goog to have some default styles that toggle between open and closed view. 

And a default separator line between each item. 

Please see this tutorial: 

https://moduscreate.com/blog/expanding-and-collapsing-elements-using-animations-in-react-native/

It has a chevron (small triangle to the right of text that changes shape when state toggled)

It has some default colors and style changes that happen when the state changes from collapsed to open and then again when back to the collapsed state.

**Comment by iRoachie** [comment]
Hey @pashute there's no reason why you can't apply the changes you requested in your own component. You can conditionally display the chevron using the `isActive` param thats passed in the `renderHeader` and `renderContent`.

**Comment by iRoachie** [comment]
This lib serves to be as general purpose as possible :)

**Comment by iRoachie** [comment]
Closing as inactive
