### ISSUE TITLE
Component width

### ISSUE THREAD

**Issue by fouratj** [oblador/react-native-collapsible#194]
Upon opening and closing all the collapsible items, the component snaps to a new width (something like half the original width), and stays so. See example before/after.

BEFORE:
![before](https://user-images.githubusercontent.com/11446404/40328408-a673a320-5d1c-11e8-91f2-f8bfb4bd2eb0.PNG)

AFTER:
![after](https://user-images.githubusercontent.com/11446404/40328409-a697cac0-5d1c-11e8-8f6f-e40cd9133d7c.PNG)

**Comment by iRoachie** [comment]
Could you check if this still occurs using [0.120](https://github.com/oblador/react-native-collapsible/releases/tag/v0.12.0) ?

**Comment by fouratj** [comment]
Hi iRoachie,

I can confirm that it is still happening on v0.120. It's weird, because it'll only occur after you have opened and closed each single one. Until then, everything is ok.

**Comment by bkitduy** [comment]
I'm faced this issue on Android. How  can we fix it ?

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
