### ISSUE TITLE
Accordion sections prop not support Realm.Results

### ISSUE THREAD

**Issue by YaoHuiJi** [oblador/react-native-collapsible#196]
When using [RealmJs](https://realm.io/docs/javascript/latest) query result as the datasource of Accordion , since [Realm.Results](https://realm.io/docs/javascript/2.6.0/api/Realm.Results.html) is not a array, but an array-like object,  and the  prop 'sections'  MUST be an array, so an error will be throwed by this function
https://github.com/oblador/react-native-collapsible/blob/ed6283a8ce7ea16e7b54fc7a5341b7a73d95f11b/Accordion.js#L74-L78

I would like to  create a pull request, but I am not sure how to change this part of logic, 

change 

`sections: PropTypes.array.isRequired`

to 

`sections:  PropTypes.oneOfType([
      PropTypes.array,
      PropTypes.shape({
        map: PropTypes.func,
      }),
    ])`

and the handleErrors func to

`
  handleErrors = () => {
    if (!this.props.sections.map) {
      throw new Error('Sections should be an array-like');
    }
  };
`
?  
looks so weird...

**Comment by iRoachie** [comment]
You can cast the results from realm as an array that you can then pass to the accordion. See https://github.com/realm/realm-js/issues/280#issuecomment-347011764

**Comment by YaoHuiJi** [comment]
thank you,I have read this realm thread before, in my code I use the function lodash.values to do the same thing, but I really do not like the unnecessary process, speaking of which maybe this should be a realm issue and I know they are working on it since 2016😢... anyway thank you for your reply

**Comment by YaoHuiJi** [comment]
Met this problem again, and I forgot I have been there few months ago...So here is my solution, just rewrite it, hope it's helpful for who gets here too.
`class AccordionForRealm extends Accordion {
    static propTypes = {
        sections: PropTypes.oneOfType([PropTypes.array, PropTypes.shape({map: PropTypes.func})])
    }
    handleErrors = () => { }
    };}`
