### ISSUE TITLE
Search functionality over sections

### ISSUE THREAD

**Issue by Bassonlinho** [oblador/react-native-collapsible#203]
Hey, great library thanks a lot!
I have both filter and search functionality implemented over the Accordion but the thing is it sometimes does not render content. Although it does search job perfectly, and renders header perfectly(which I know based on number of sections I have in my renderHeader function). Also I console logged the sections after search and the one missing is actually there, its logged in console but just doesn't appear in list.
I'm providing you screenshot and if it's necessary  I'll provide my code as well. Do you have a clue what could be wrong?
![screenshot_20180530-201529](https://user-images.githubusercontent.com/13332888/40739480-a458ccc4-6446-11e8-8cef-b42d700a8a4e.png)

**Comment by Bassonlinho** [comment]
As far as I could see while playing with it, sometimes it takes height of previous section(before search was applied), renders content correctly but renders white space below as well. What does bother me is the fact that renderHeader ALWAYS rerendered without problem, while renderContent sometimes buggs out, sometimes not. I'm attaching screenshots before search applied and after. Did anyone exp. something like this?
![screenshot_20180531-113724](https://user-images.githubusercontent.com/13332888/40775072-76678c98-64c7-11e8-94d1-74dd68837bc9.png)
![screenshot_20180531-113901](https://user-images.githubusercontent.com/13332888/40775066-749ce228-64c7-11e8-912e-dc2b1f67f089.png)

**Comment by iRoachie** [comment]
https://github.com/oblador/react-native-collapsible/pull/197 Should fix this.

**Comment by Bassonlinho** [comment]
Isn't this pull request related to Collapsible? I'm using Accordion because I work with live data that I fetch from server

**Comment by iRoachie** [comment]
Accordion uses collapsible underneath

**Comment by Bassonlinho** [comment]
Aha, okay. So it will be fixed in next release? 
Just to know, because I like how stuff works and would like to stick to this library.

**Comment by iRoachie** [comment]
Yessir! Should release a version this weekend

**Comment by Bassonlinho** [comment]
Great man, nice work!
I'll close this. Have a nice weekend :+1:

**Comment by Bassonlinho** [comment]
I suppose you are busy but, any updates on when should next release arrive?

**Comment by iRoachie** [comment]
Released in [0.120](https://github.com/oblador/react-native-collapsible/releases/tag/v0.12.0)
