### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by SirPhemmiey** [oblador/react-native-collapsible#204]
Hi guys, 
Buttons in the _renderContent function doesn't respond to events. 
Take a look at this
` return (
      <View >
          <View style={styles.contentContainer}>
          <Text style={styles.contentHeader}>Provider Name</Text>
        <Text style={styles.contentText}>{section['Provider'].name}</Text>
      </View>
      <View style={styles.contentContainer}>
          <Text style={styles.contentHeader}>Provider Phone</Text>
        <Text style={styles.contentText}>{section['Provider'].phone}</Text>
      </View>
      <View style={styles.contentContainer}>
          <Text style={styles.contentHeader}>Service Type</Text>
        <Text style={styles.contentText}>{section['Service'].name}</Text>
      </View>
      <View style={styles.contentContainer}>
          <Text style={styles.contentHeader}>Status</Text>
        <Text style={[styles.contentText]}>{section['Schedule'].status}</Text>
      </View>
     
      <View>
      <Button small style={styles.button} onPress={() => {
            this.setModalVisible(true);
          }}>
      {
          section['Schedule'].status = 'pending' ? 
              <Text style={styles.buttonText}>Mark as Complete</Text>: 
              <Text style={styles.buttonText}>Marked as Complete</Text>
      }
      </Button>
      </View>
      </View>
    );`
When i click the button it says Undefined is not a function. Even when i tried to use `this.setState`

Note: Buttons outside the accordion responds.

**Comment by Bassonlinho** [comment]
Set your Accordion renderContent like this
renderContent={(section, i, isActive) => this._renderContent(section, i, isActive)}

And then in your _renderContent function you can do:
this.setModalVisible.bind(this, true)

Hope it helps

**Comment by SirPhemmiey** [comment]
Works great. Thanks!
