### ISSUE TITLE
example does not work on android via react-native run-android

### ISSUE THREAD

**Issue by kristoferpelchat** [oblador/react-native-collapsible#205]
react-native run-ios works perfect and looks fantastic! I was going to customize some backgrounds and fonts when I saw it does not work in android. Is there an extra file/flag I am missing?

**Comment by iRoachie** [comment]
What error do you get on android?

**Comment by kristoferpelchat** [comment]
What seemed to happen is I was not seeing anything come up in the ScrollView. I was using your example with the Accordion and finding it was rendering in iOS but not in Android. This morning I initialized everything and completely rebuilt with react-native. ALL SEEMS TO BE WORKING NOW! :)

I am happy to close this issue out but one question. I am getting the following warning in both iOS and Android. Is this a known issue...any way to fix this:

"Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks."

Thanks so much in advance!
Kris

**Comment by iRoachie** [comment]
Yea that last part about the isMounted we have a PR already made for it. So that'll be merged soon.

**Comment by kristoferpelchat** [comment]
Fantastic! You guys have a great component! Thanks for the VERY quick response and help!

**Comment by iRoachie** [comment]
Thanks mate! Happy coding
