### ISSUE TITLE
Content View Click event 

### ISSUE THREAD

**Issue by shivsuthanm-odhub** [oblador/react-native-collapsible#206]
How to manage Touchable click event in content render?
```
<Accordion
                        sections={response}
                        initiallyActiveSection={1}
                        touchableComponent={TouchableOpacity}
                        renderHeader={this._renderHeader}
                        renderContent={this._renderContent}
                        onChange={this._setSection.bind(this)}
/>
```
Please find below content render function.

```
    _renderContent(section, i, isActive) {
        return (

                <TouchableOpacity onPress={()=>{Here I wanna call a parent function)}} />

        );
    }

```

**Comment by iRoachie** [comment]
What's the problem?

**Comment by maartenvandillen** [comment]
@iRoachie I think I have the same problem. My content contains a list of TouchableOpacity's with their own onPress handlers. When clicking one of the TouchableOpacity's the content container closes instead of the onPress handler getting called.

**Comment by iRoachie** [comment]
It's definitely a bug I've seen come up before. I didn't write the original code for it, I came onto the project as a maintainer. I'll see if I can look into it and fix the problem.

**Comment by maartenvandillen** [comment]
I think I solved it by setting the keyboardShouldPersistTaps prop of the parent ScrollView

**Comment by gagantaneja** [comment]
try creating the function inside the `renderContent() {` before the `return (` statement for example:`renderContent(section, _, isActive) {
		const gotoDeposit = () => {
			Actions.deposit();
		};
		return (`

and while calling it don't use this. Call it straightaway by the function name . 
example : `<TouchableOpacity style={styles.dWButton} onPress={gotoDeposit}>`

**Comment by KirankumarDafda** [comment]
@gagantaneja this makes sense but for the same I am still confused, as I want to redirect to another screen using navigate from react navigation but its giving me error **undefined is not a function (evaluating '_this2.redirectoedit()') error in react native app**

What I am doing is

`     editPrice = () => { 
		const { navigate } = this.props.navigation;
		navigate("EditPage");
	}`

**Comment by bigujun** [comment]
Someone solved it?

**Comment by reimertz** [comment]
You can wrap your element and prevent event from bubbling up to `react-native-collapsible` 

```
<TouchableWithoutFeedback onPress={event => event.stopPropagation()>
  <YourContentHere/>
</TouchableWithoutFeedback>
```
or add `onResponderRelease={event => event.stopPropagation()}` to element with `onPress`.

**Comment by iRoachie** [comment]
Can someone confirm if [1.2.0](https://github.com/oblador/react-native-collapsible/releases/tag/v1.2.0) fixes this with the pointerEvents override?

**Comment by Vieshanis** [comment]
@iRoachie it doesn't. Still can't click and also now when drawer is collapsing the whole Accordion somehow becomes transparent
