### ISSUE TITLE
Error renderContent

### ISSUE THREAD

**Issue by issnoe** [oblador/react-native-collapsible#207]
export default class AccordionView extends Component {
    constructor(props){
        super(props);
    }
    _renderSectionTitle(section) {
        return (
            <View style={styles.content}>
                <Text>{section.content}</Text>
            </View>
        );
    }

    _renderHeader(section) {
        return (
            <View style={styles.header}>
                <Text style={styles.headerText}>{section.title}</Text>
            </View>
        );
    }

    _renderContent(section) {
      
        return (
            <View style={styles.content}>
                <Text>{section.content}</Text>
            </View>
        );
    }

    render() {
        return (
            <View>
                <Accordion
                    sections={SECTIONS}
                    renderSectionTitle={this._renderSectionTitle}
                    renderHeader={this._renderHeader}
                    renderContent={this._renderContent}
                />
            </View>
        )
    }
}

**Comment by iRoachie** [comment]
I don't understand your issue. What error are you receiving?

**Comment by iRoachie** [comment]
Closing as inactive.
