### ISSUE TITLE
Add more view in content error

### ISSUE THREAD

**Issue by cola91hn** [oblador/react-native-collapsible#208]
I have a issue when i add more view in content. 
var CONTENT = [
      {
        title: 'ABC',
        content: <WOAB updateService={obj}/>
      },
      {
        title: 'ABC 1',
        content: <WOAB updateService={obj}/>
      },
      {
        title: 'ABC 2',
        content: <WOAB updateService={obj}/>
      },
      {
        title: 'ABC 3',
        content: <WOAB updateService={obj}/>
      }
    ];

'WOAB' is a child component. 
It's run good on IOS but fail on Android.
Error: Unexpected view type nested under text node.

**Comment by iRoachie** [comment]
Can you recreate your error on https://snack.expo.io? Your issue just shows an array and doesn't explain the issue or the code that produced it.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
