### ISSUE TITLE
Gets the child click event

### ISSUE THREAD

**Issue by ZSH-HSZ** [oblador/react-native-collapsible#209]
![image](https://user-images.githubusercontent.com/31639046/41765764-a1e55676-7637-11e8-9158-180ff707c628.png)
 Is there an event outside that lets me know that I clicked on the child？

**Comment by iRoachie** [comment]
Is there any reason you can put your own Touchable inside?

**Comment by EzeRangel** [comment]
@iRoachie I have this case and don't know how to proceed.

![captura de pantalla 2018-08-29 a la s 13 30 23](https://user-images.githubusercontent.com/1395261/44810726-d9599580-ab8f-11e8-8f2a-71b888134dae.png)

**Comment by EzeRangel** [comment]
I have tweaked in the `Collapsible` component and found the main `Animated.View` has this

 `pointerEvents={collapsed ? 'none' : 'auto'}` 

is there any reason why the the view prevents touch while is collapsed?

**Comment by gamingumar** [comment]
You can enable children touch events with ```enablePointerEvents```

**Comment by AneesFolio3** [comment]
Any update on it?
