### ISSUE TITLE
isMounted is deprecated

### ISSUE THREAD

**Issue by markentingh** [oblador/react-native-collapsible#212]
After importing & using this component in my React Native project (0.55.4), I get a warning message upon loading:

> Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

The warning appears whenever I change the `collapsed` prop to `true` as well.

**Comment by iRoachie** [comment]
Duplicate of #162

**Comment by markentingh** [comment]
Cool, I did search for "isMounted" before posting my issue, thanks for such a quick response

**Comment by iRoachie** [comment]
No problem, haven't gotten around to looking over the PR as yet.

**Comment by markentingh** [comment]
I believe in you :)
