### ISSUE TITLE
Wrong calculations & cut off text

### ISSUE THREAD

**Issue by mxmtsk** [oblador/react-native-collapsible#215]
When using padding within the content it seems that text get's cut off so I assume something is calculated wrong. See the last word in the screenshot:

<img width="338" alt="bildschirmfoto 2018-07-04 um 21 58 49" src="https://user-images.githubusercontent.com/4848184/42292834-c335d682-7fd5-11e8-9b89-76d662a24f31.png">

Also, a weird space is visible below the expanded content. This get's especially visible in the last item of an accordion:

<img width="344" alt="bildschirmfoto 2018-07-04 um 21 58 55" src="https://user-images.githubusercontent.com/4848184/42292831-be6ada6c-7fd5-11e8-84da-70f5c7e8e6c0.png">

This is my code:

```Javascript
class HelpIndex extends React.Component {
  static navigationOptions = {
    headerTitle: "Hilfe",
  };

  _renderSectionTitle(section) {
    return <View style={styles.content} />;
  }

  _renderHeader(section) {
    return (
      <View style={styles.header}>
        <Txt medium style={styles.headerText}>{section.title}</Txt>
      </View>
    );
  }

  _renderContent(section) {
    return (
      <View style={styles.content}>
        <View style={styles.contentInner}>
          <Txt style={styles.body}>{section.body}</Txt>
        </View>
      </View>
    );
  }

  render() {
    return (
      <Container>
        <ScrollContainer withPadding>
            <Accordion
              sections={faq}
              renderSectionTitle={this._renderSectionTitle}
              renderHeader={this._renderHeader}
              renderContent={this._renderContent}
              touchableProps={{
                underlayColor: 'transparent',
              }}
            />
        </ScrollContainer>
      </Container>
    );
  }
}
```

Applied styles:
```Javascript
export default StyleSheet.create({
  content: {
    backgroundColor: 'rgba(57,47,82,0.1)',
  },
  contentInner: {
    padding: 20,
  },
  container: {
    backgroundColor: '#fff',
  },
  headerText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#59568B',
  },
  header: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(57,47,82,0.1)',
  },
  body: {
    fontSize: 14,
    lineHeight: 22,
    color: '#392F52',
  },
});
```

**Comment by mxmtsk** [comment]
Hey @iRoachie thanks, haha!

You can find the snack here:
https://snack.expo.io/@mxmtsk/collapsible-test

**Comment by Taglohner** [comment]
Hi mxmtsk,  in fact I'm having the same issue with margin, I managed to arrange my view using padding instead.

**Comment by nguyenvanphuc2203** [comment]
i have same issue

**Comment by mxmtsk** [comment]
@Taglohner I haven't used any margin though...
@iRoachie Did you have a chance to take a look at this? We're close to rolling out our app and this is one of the last bugs we encounter

**Comment by iRoachie** [comment]
This is such a weird bug, seems like it's an issue with lineHeight, cause without setting it, it works as expected.

Everything seems to work after adding `flex: 1` to the `contentInner` style. https://snack.expo.io/rJj30SMEQ

**Comment by WarHatch** [comment]
@mxmtsk are you sure this is not just a ScrollContainer issue? I had the same problem recently where I passed padding to `style` instead of `contentContainerStyle`.
Here's the link to the [ScrollContainer issue](https://github.com/facebook/react-native/issues/2914)

**Comment by mxmtsk** [comment]
@iRoachie I can confirm that your "workaround" does work, so the issue is resolved for me (but maybe not for this library in general) - thanks!

@WarHatch Yes I'm sure, I'm not passing any styling to `ScrollView` in my component

**Comment by iRoachie** [comment]
Awesome glad I could help. Not sure how we could fix in the future, but I'll look into it more closely if someone else brings it up. Beautiful app man!

**Comment by mxmtsk** [comment]
@iRoachie Thank you very much. Feel free to add it as an example for the component of how it can be styled if you like it so much.

**Comment by iRoachie** [comment]
Sure thing @mxmtsk let me know when your app goes live!

**Comment by Youn-ha** [comment]
For anyone suffering with this strange bug...
I'm using Styled Components with React Native,
and giving `flex: 1` styling to content container didn't work.

Instead, this one worked.

```
  flex: 1;
  flex-direction: row;
  flex-wrap: wrap;
```

Hope this can help somebody using Styled Components.
