### ISSUE TITLE
Height of collapsible view doesn't change

### ISSUE THREAD

**Issue by nicomontanari98** [oblador/react-native-collapsible#217]
If component is collapsed it's height doesn't change
I'm using the version 0.12.0

![Gif](https://user-images.githubusercontent.com/15747776/42504342-be1315ba-843b-11e8-83fa-c154eb7e8a10.gif)

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by nicomontanari98** [comment]
I resolved it, the error was that i assigned flexWrap: 'wrap' to main container and to collapsible container.
