### ISSUE TITLE
initiallyActiveSection 0 does not work (the content area NOT expanded as expected) 

### ISSUE THREAD

**Issue by ayehia** [oblador/react-native-collapsible#219]
The Accordion placed in react native Modal

I tried to set  **initiallyActiveSection** and **activeSection** to ZERO for expanding the first item

The active flag passed correctly to **renderHeader** callback but the content arent not opened

![image](https://user-images.githubusercontent.com/12626365/42607405-f58d44dc-8582-11e8-8d3c-3701ffd91c1c.png)

PS: everything works as expected (expand, collapse, animation, ... etc) the issue only in expanding a default item.

I tried a lot of solutions but it still not working :( .. please help

**Comment by iRoachie** [comment]
You can see here that the Accordion works with no problem https://snack.expo.io/B1TvOSfVX

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
