### ISSUE TITLE
Unhandled JS Exception

### ISSUE THREAD

**Issue by L-Jovi** [oblador/react-native-collapsible#22]
when I click faster will get below error

![image](https://cloud.githubusercontent.com/assets/7262199/13597212/46da6122-e552-11e5-9e1a-63ae473e0fff.png)

above error can't appear when I click slowly :(

any idea?

thanks for you time.

**Comment by oblador** [comment]
Are you using the latest version?

**Comment by L-Jovi** [comment]
@oblador  I use `react-native-collapsible` version: 0.5.5 and `react-native` version: ^0.19.0

**Comment by L-Jovi** [comment]
@oblador  I integrate `import Accordion from 'react-native-collapsible/Accordion';` to my application and I never see this error again, but at first I always encounter red screen of __react-native-collapsible/Example__.

I don't think that 'react-native-collapsible` cause the bug, maybe another reason from __react-native-collapsible/Example__'s dependencies, so I close this issue.

thanks for your reply.
