### ISSUE TITLE
content not break line in IOS, android work fine

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [oblador/react-native-collapsible#220]
![screen shot 2018-07-13 at 9 45 53 am](https://user-images.githubusercontent.com/33291479/42669799-95ec92bc-8681-11e8-9fc5-23af7ffbafa7.png)

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by anhpt-cse** [comment]
seems like there is a miscalculation of content height. You could maybe fix this problem by setting style of your text container to flex: 1
