### ISSUE TITLE
Any way to render content by passing an array instead of atomic value?

### ISSUE THREAD

**Issue by Desz01ate** [oblador/react-native-collapsible#221]
assume that I had an object that is structure like this
```
{
	Title : 'A',
	Header : 'Header A',
	Content : [
		{
			key:'x',
			value:1
                },
		{
			key:'x',
			value:2
                }
	],
	Title : 'B',
	Header : 'Header B',
	Content : [
		{
			key:'x',
			value:1
                },
		{
			key:'x',
			value:2
                }
	],
}
```
and I need to use "Content" as a source of Accordion renderContent how can I achieve this?
I've try sending second parameter as index to 

```
 _renderContent(section, index) {
    return (
      <View>
        <Text>{section.Content[index].value}</Text>
      </View>
    )
  }
```

 but it doesn't seem to work.

**Comment by Desz01ate** [comment]
problem solved.

**Comment by mahdidavoodi7** [comment]
how you solved this problem ?

**Comment by kajalbhanse** [comment]
Hi.... Can you please let me know how to solve this problem. Same situation with me. Please help

**Comment by Desz01ate** [comment]
It’s been a long time since I’ve encountered this problem and it’s a source code of my old company so  I can’t help you with this, sorry.

**Comment by KirankumarDafda** [comment]
If anyone have solution of this, can you please share or suggest any alternative way to get rid of this problem. Thanks
