### ISSUE TITLE
Example for using collapsible in sectionList

### ISSUE THREAD

**Issue by livein21st** [oblador/react-native-collapsible#222]
Hi, it's a great library. However I wonder if you can provide some example of using it in react native SectionList. also allowing only one section to open at a time and other are closed when clicked.

for example like that https://www.npmjs.com/package/react-native-expandable-section-list

Thanks again.

**Comment by iRoachie** [comment]
I don't this library will be able to work with react native's SectionList as they are doing the same things. 

You can just use the Accordion from this package. Here's an example https://snack.expo.io/rkuMoHzVm

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
