### ISSUE TITLE
After setting up activeSection, other options can not be opened, and the current option cannot be closed.

### ISSUE THREAD

**Issue by kmlidc** [oblador/react-native-collapsible#226]
设置了 activeSection 后，无法打开其他选项，也无法关闭当前选项

After setting up activeSection, other options can not be opened, and the current option cannot be closed.

**Comment by maikmacs** [comment]
I have the same issue and get solvet with this https://github.com/oblador/react-native-collapsible/issues/139

**Comment by maikmacs** [comment]
I had the same problem and I could solve it with this https://github.com/oblador/react-native-collapsible/issues/139

**Comment by iRoachie** [comment]
Closing as duplicate of #139
