### ISSUE TITLE
react-native-calendars inside collapsible view. (help needed)

### ISSUE THREAD

**Issue by kinza88** [oblador/react-native-collapsible#230]
I am using calendar view inside collapsable view. I tap on a button, collapsible view opens and shows the calendar with current month. Till here things work fine. 
But as soon as I as click the next/previous month arrow. Collapsible view gets closed. When I tap it again it doesn't get opened with correct height (maybe because the calendar is still loading). Upon 3rd tap calendar view opens with the next month. 

**Things I have tried:**
1. Putting calendar in a view of static height (ie 350) so that collapsable view opens even if the calendar is not loaded. 
2. When user taps next/previous arrows, update the state and make loading variable true. Now the component will be reloaded and it will do conditional loading based on "loading" state variable. When next month gets loaded update the state again and make loading variable false. Here is the code related to the above described logic, for more understanding:

```
state = {
        reservedDateColor : 'red',
        loading :  false
    };

render()
    {
        if (this.state.loading == false)
        {
           return (
               <View style = {Styles.container}>
                   <Calendar style = {Styles.calendar}
                    markingType={'custom'}
                    markedDates={dict}
                    onPressArrowRight={addMonth => addMonth(this.setState({loading: true}))}
                    onPressArrowLeft={substractMonth => substractMonth(this.setState({loading: true}))}
                    onMonthChange={(month) => {this.setState({loading: false})}}
                    />
                </View>
            ) 
        }
        else
        {
            return (
                <View style = {Styles.container}>
                    <Text> Loading </Text>
                </View>
            )
        }
    }
```
These 2 tries didn't really help. Any help in this regard would be appreciated.

**Comment by iRoachie** [comment]
Hey @kinza88, can you try to set up a small example using https://snack.expo.io?

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by kinza88** [comment]
Hi @iRoachie 
Currently this task is on hold in my project. When I will resume working on this I will add the issue again (if needed). 

Cheers!
