### ISSUE TITLE
Unable to expand view in iOS on RN50 (@0.50.4) and react-native-collapsible @0.13.0 if the content is a FlatList

### ISSUE THREAD

**Issue by progamr** [oblador/react-native-collapsible#236]
### This as the accordion

`<Accordion
          style={{marginLeft: 15, marginRight: 15}}
           sections={SECTIONS}
           renderSectionTitle={this._renderSectionTitle}
           renderHeader={this._renderHeader}
           renderContent={this._renderContent}
           underlayColor={'transparent'}
                        />`

### and this is my three main functions
`    _renderSectionTitle(section) {
        return (
            <View style={{flex: 1, height: 40, justifyContent: 'center'}}>
                <Text style={{marginLeft: 15, fontSize: 16, color: colors.black0}}>{section.title}</Text>
            </View>
        );
    }

    _renderHeader(section) {
        return (
            <View style={{}}>
                <Text style={{fontSize: 14, color: colors.gray01, marginLeft: 5}}>{section.header}</Text>
            </View>
        );
    }

    _renderContent(section) {
        return (
            <FlatList data={this.comments} renderItem={this.renderTopicComment} keyExtractor={(item, index) => index} />
        );
    }`
**and this is the render item of FlatList if needed**
`renderTopicComment({item}) {
        return (
            <View style={{}}>
                <Image source={require('./Leadership.jpg')} style={[coursesStyles.courseLikeAvatar, {width: 35, height: 35, borderRadius: 17.5}]}/>
                <View>
                    <Text>Amr Mohamed</Text>
                    <Text>{item.comment}</Text>
                </View>
            </View>
        );
    }`

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
