### ISSUE TITLE
Collapsible within ListView within ViewPagerAndroid

### ISSUE THREAD

**Issue by ms88privat** [oblador/react-native-collapsible#24]
In my project I got a ListView with this row layout:
```javascript
<TouchableWithoutFeedback onPress={this.props.setExpandedProduct}>
        <View style={[s.container]}>
          <ProductInfoComponent product={this.props.product}/>
          <Collapsible collapsed={this.props.isCollapsed}>
            <View style={s.productPriceContainer}>
              {productPrices && productPrices.map((id) =>
                <ProductPriceContainer key={id} productPriceId={id} onAdd={this.handleAdd}/>
              )}
            </View>
          </Collapsible>
        </View>
      </TouchableWithoutFeedback>
```

This is working fine in iOS. In Android it is working fine too until I wrap my ListView in a ViewPagerAndroid. It will not expand OR collapse anymore.

This version (without Collapsible) still works like expected.
```js
<TouchableWithoutFeedback onPress={this.props.setExpandedProduct}>
        <View style={[s.container]}>
          <ProductInfoComponent product={this.props.product}/>
          {!this.props.isCollapsed && (
               <View style={s.productPriceContainer}>
                  {productPrices && productPrices.map((id) =>
                     <ProductPriceContainer key={id} productPriceId={id} onAdd={this.handleAdd}/>
                   )}
                </View>
            )}
        </View>
      </TouchableWithoutFeedback>
```

I tested some more (before posting this issue):

It does work on my device (Android 4.4) and on my other Emulator devices. Only the S6 (Android 6.0) does not work!

![image](https://cloud.githubusercontent.com/assets/6705521/13893650/b3d36484-ed60-11e5-86b2-e62618a6e800.png)

The question is, if this is a real issue with Android 6.0 or if it is only an emulator bug?

**Comment by oblador** [comment]
That sounds very strange indeed, IIRC I've developed with Android 6 but don't see how there could be much difference since this is a pure JS module. Can you provide me a runnable gist so I can debug?

**Comment by ms88privat** [comment]
It is working after I restarted this morning... sry about that.
