### ISSUE TITLE
Incorrect semantic versioning 0.14.0

### ISSUE THREAD

**Issue by fierysolid** [oblador/react-native-collapsible#242]
The version should have gone from 0.13.0 to 1.0.0 since the Accordion additions in 0.14.0 are a breaking change and are not backward compatible with 0.13.0. The incorrect versioning is going to break peoples apps if they update their modules thinking its backward compatible.

**Comment by iRoachie** [comment]
Okay, will do 1.0

**Comment by fierysolid** [comment]
Thanks man

**Comment by iRoachie** [comment]
I don't have access myself though so after I'll need @oblador to deprecate v0.14.0

**Comment by iRoachie** [comment]
Okay 1.0.0 published on npm. I just realized I do have permission. Just removed 0.14.0 and updated the tags and release. Thanks again!
