### ISSUE TITLE
Section Items

### ISSUE THREAD

**Issue by emrkuru** [oblador/react-native-collapsible#245]
I would design an accordion that has an header and include a form which get user information like name,surname etc.

How could i achieve this situation ?.. Instead of array string

Sincerely

**Comment by emrkuru** [comment]
I got answer in previous issues, tnx

**Comment by mrinal-roy-au2** [comment]
@emrkuru could you please mention which previous issue you referred? I am facing similar issue to render checkbox & slider in each section.
