### ISSUE TITLE
[ANDROID]- App crashing

### ISSUE THREAD

**Issue by arpitjain-in** [oblador/react-native-collapsible#249]
Hi,
I'm using `react-native-collapsible` in side navigation with native base component. It is crashing and showing below error:-

``` Cannot add a child that doesn't have a YogaNode to a parent without measure function! (Trying a add a RCTRawText [text: "/>"] to a 'RCTView').```

Please help.

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by arpitjain-in** [comment]
Thanks @iRoachie for quick jump into this. Creating snack will take some time.. but I can mention my code snippet here

```
<Content>
          {/* <Accordion
            sections={SECTIONS}
            activeSections={this.state.activeSections}
            //renderSectionTitle={this._renderSectionTitle}
            renderHeader={this._renderHeader}
            renderContent={() => this._renderContent(user)}
            onChange={this._updateSections}
          /> */}
```

**Comment by iRoachie** [comment]
There's no way for me to know why your app wouldn't work without replicating the behaviour in a snack.

The error you received happens when you're trying to add raw text into a view.
e.g 
```jsx
<View>My name is George</View>

// Should be
<View><Text>My name is George</Text></View>
```

**Comment by arpitjain-in** [comment]
My bad...
