### ISSUE TITLE
Can't install new version

### ISSUE THREAD

**Issue by mnlbox** [oblador/react-native-collapsible#252]
Hi,
I'm working with version 0.13.0 and today want's to update my app to new version but I see this error:
```
arning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
error react-native-collapsible@1.2.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0". Got "9.0.0"
error Found incompatible module
```
Have you any suggestion?

**Comment by iRoachie** [comment]
Does it prevent you from installing the package or is it only a warning

**Comment by iRoachie** [comment]
Will fix this as soon as I get in from work. This is probably due to https://github.com/oblador/react-native-collapsible/pull/224

Wasn't aware of this side-effect. Sorry about that.

**Comment by iRoachie** [comment]
Think we can just remove this at this point. https://github.com/oblador/react-native-collapsible/blob/master/package.json#L11.

If anyone wants to fix this feel free to do so.

**Comment by jgfidelis** [comment]
aham, no problem. I will revert to 1.1.0 for now

**Comment by iRoachie** [comment]
1.2.1 released
