### ISSUE TITLE
Cannot find module 'react-native-collapsible/Accordion'

### ISSUE THREAD

**Issue by Anujmoglix** [oblador/react-native-collapsible#255]
I am getting same issue in "react-native-collapsible": "^1.2.1",

**Comment by iRoachie** [comment]
Can you post a screenshot of the actual error

**Comment by Anujmoglix** [comment]
I am not using this plugin now but it was showing issue .

**Comment by iRoachie** [comment]
I am not understanding. Where/how did you see this error?

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by parthv21** [comment]
I think he is talking about this:
<img width="983" alt="Screen Shot 2019-07-02 at 9 41 20 AM" src="https://user-images.githubusercontent.com/17941287/60482049-a8fdee80-9cad-11e9-86fa-b2e06707bad1.png">

**Comment by iRoachie** [comment]
It's a default export.  See readme https://github.com/oblador/react-native-collapsible#accordion-usage

```jsx
import Accordion from 'react-native-collapsible/Accordion'
```
