### ISSUE TITLE
Collapsible pushing item out of screen

### ISSUE THREAD

**Issue by renato-bvdash** [oblador/react-native-collapsible#263]
I am having the current issue:
https://stackoverflow.com/questions/53435735/how-to-display-elements-after-a-collapsible-within-the-screen
Figured I would post it here just in case you have some alternate solution.

Seems similar to #5 except that I'm not sure how setting a height would help me, specially since the height of the two `<TouchableOpacity>`s changes depending on what their contents are.

The idea is to have both `<TouchableOpacity>`s within the screen and have the component in the Collapsible resize accordingly given that it returns a `<FlatList>`.

Any pointers would be of great help. Thank you.

**Comment by iRoachie** [comment]
Do you have a visual of this? Or can you recreate this in http://snack.expo.io/?

**Comment by renato-bvdash** [comment]
Sorry I took all day. Here is a demonstration:

https://snack.expo.io/@yokhen/collapsible-flatlist-brainwreck

**Comment by iRoachie** [comment]
Kk I looked at the snack, this issue is a duplicate of #86
