### ISSUE TITLE
Example : undefined is not an object (evaluating 'this state.collapsed')

### ISSUE THREAD

**Issue by KevinHu2014** [oblador/react-native-collapsible#27]
While trying the Example ,
 I got an error `undefined is not an object (evaluating 'this state.collapsed')` after pressing the TouchableHighlight

![test-mainactivity-05252016013043](https://cloud.githubusercontent.com/assets/7204070/15513690/5bcab426-2218-11e6-80a6-ae0cbf3b02c8.png)

**Comment by oblador** [comment]
Fixed now!
