### ISSUE TITLE
FlatList is not scrolling.

### ISSUE THREAD

**Issue by emirselvi** [oblador/react-native-collapsible#276]
Hello,
In my accordion component I can't load my flatlist as expected. Flatlist is not scrollable in accordion component.
This is my section instance.
`const SECTIONS = [
            {
                title: 'title',
                content: flatlist,
            },
            {
                title: 'title',
                content: flatlist1,
            },
        ];`

and this is how I use accordion component.
`<Accordion
                            activeSections={this.state.activeSections}
                            sections={SECTIONS}
                            renderContent={_renderContent}
                            renderHeader={_renderHeader}
                            onChange={_updateSections}
                        />`

How can I make my flatlist scrollable?

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this? I'd need a full example to debug.
