### ISSUE TITLE
horizontally collapsible support

### ISSUE THREAD

**Issue by KevinHu2014** [oblador/react-native-collapsible#28]
Is horizontally collapsible (left to right) support?

**Comment by oblador** [comment]
It's not currently possible, what is your use case? Horizontal scroll view?

**Comment by KevinHu2014** [comment]
I am trying to make a sidebar that is collapsible.

**Comment by oblador** [comment]
Then you're better of with either of these: 

https://github.com/root-two/react-native-drawer
https://github.com/react-native-fellowship/react-native-side-menu

**Comment by KevinHu2014** [comment]
@oblador Thanks
