### ISSUE TITLE
Accordion animation smooth but Collapsible is chunky?

### ISSUE THREAD

**Issue by ds8k** [oblador/react-native-collapsible#284]
On the same page I have a component using Collapsible and another component using Accordion. The Accordion animates really smoothly even in Development mode, but the Collapsible one chugs real hard. Any ideas as to why? I have two "ReactText" components inside the collapsible, amounting to maybe 6 lines of text max.

"react": "16.8.6",
"react-native": "0.59.3",
"react-native-collapsible": "1.4.0",

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by ds8k** [comment]
I don't have the time to do this right now so there's no reason for me to keep this open. Thanks for the response!
