### ISSUE TITLE
undefined is not an object (evaluating 'activeSections.includes')

### ISSUE THREAD

**Issue by apsuva** [oblador/react-native-collapsible#289]
my codes working with react-native-collapsible 0.10.0, react 16.2.0, react-native 0.55.4

upgrade after it doesn't work.
undefined is not an object (evaluating 'activeSections.includes')

    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-collapsible": "^1.4.0"

    <Accordion
        activeSection={this.state.activeSection}
        sections={this.state.sections}
        renderHeader={this._renderHeader.bind(this)}
        renderContent={this._renderContent.bind(this)}
        duration={200}
        onChange={this._setSection.bind(this)}
        underlayColor = "transparent"
    />

**Comment by arcollector** [comment]
I have the same problem, i did back to 0.12.0 version, but the problems persist, so i run the command `npm start -- --reset-cache` and it did the magic

**Comment by lyqht** [comment]
im trying out `"react-native-collapsible": "^1.4.0"` as well with the demo that he showed on the readme, it works fine.
be careful of the following prop:
`activeSection` should be `activeSections` after upgrading to `v1.4.0`
`activeSections` expect an array instead of a number now.

**Comment by iRoachie** [comment]
Correct @lyqht the prop is called `activeSections`.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by Hel5ing** [comment]
try this,
**activeSections={this.state.activeSections}**
and the s to the parameter and the value

**Comment by apsuva** [comment]
upgrade after my solution : 

before : 
` this.state = {
      activeSection: false,
    };
`
 `<Accordion activeSection={this.state.activeSection} />`

after : 
` this.state = {
      activeSection: [0],
    };
`
` <Accordion activeSections={this.state.activeSection} />`
