### ISSUE TITLE
VirtualizedList in the accordion component

### ISSUE THREAD

**Issue by libeanim** [oblador/react-native-collapsible#291]
Hi guys,

Thanks for your work!

Was just wondering why no [VirtualizedList](https://facebook.github.io/react-native/docs/virtualizedlist.html) or one of it's implementations like [FlatList](https://facebook.github.io/react-native/docs/sectionlist) is used in the accordion component?

Using a `VirtualizedList` has performance gains for long lists and afaik no negative impact for short ones.

Or am I missing something why a `VirtualisedList` shouldn't be used here?

Cheers,
Andreas

**Comment by barakoles** [comment]
Yeah, I think I will have to move out from this lib because of this

**Comment by Albert0405** [comment]
@iRoachie hi any plans for using Flatlist in Accordion? Also would you consider using `react-native-reanimated`? It might fix my problem about using `react-navigation` #297

**Comment by iRoachie** [comment]
I've already started working on it. Just having some issues with content changing within the collapsible. https://github.com/iRoachie/collapse/blob/master/Accordion.tsx#L113

**Comment by Albert0405** [comment]
@iRoachie :(

Any news?

**Comment by iRoachie** [comment]
I haven’t been getting it to work, have to try some new approach

**Comment by libeanim** [comment]
@iRoachie What problems did you run into/where did it break?

**Comment by iRoachie** [comment]
@libeanim The recalculation after an element inside changes

**Comment by YobertyGarcia** [comment]
Any updates about this? I'm having some trouble with a FlatList and a collapsible component :(

**Comment by oblador** [comment]
Released as opt-in prop in 1.6.0
