### ISSUE TITLE
When ActiveSessions property changes, all headers and content are re-rendered

### ISSUE THREAD

**Issue by Ahnert1** [oblador/react-native-collapsible#293]
Any time I tap on an item in my `<Accordion>`, the `renderHeader()` and `renderContent()` methods are called for **ALL** items in the list, which creates a very slow/laggy animation on the accordion. This is only an issue when list has more than ~15 items or so.  (Sometimes my `<Accordion>` has 100+ items)

Am I implementing something wrong?  I assume that the `renderHeader()` and `renderContent()`methods should NOT be called when the `activeSessions` prop is changed.

**Comment by LuizDoPc** [comment]
having the same issue here. There something that we can do to go around the problem while fix is in progress?

**Comment by iRoachie** [comment]
This is the expected behaviour. The `renderHeader` and `renderContent` methods each have an `isActive` argument passed to them that needs to be updated when `activeSessions` change. This is how applying active styling is done.

**Comment by zaptrem** [comment]
@iRoachie Is there any way to pass isActive to the render function so I can add an if statement and only render if that section is open?

**Comment by iRoachie** [comment]
@zaptrem If you see the props in the readme, `isActive` is passed to the renderContent function https://github.com/oblador/react-native-collapsible#properties-1

**Comment by zaptrem** [comment]
```
    _renderContent = (section, isActive) => {
        // In the future only render if selected
        console.log(isActive);
        if (isActive) return (
            <View style={styles.content}>
                {
                    <RecordingPlayer recording={section} />
                }
            </View>
        );
        return {};
    };
```
This crashes with "Invariant Violation: Objects are not valid as React child (found object with keys {}). If you meant to render a collection of children, use an array instead"

**Comment by iRoachie** [comment]
Of course it crashes, you are surrounding the jsx with object braces:

```diff
  if (isActive) return (
            <View style={styles.content}>
-                {
                    <RecordingPlayer recording={section} />
-                }
            </View>
        );
-        return {};
```


You are returning an object, that's why you see the error.
```jsx
if (isActive) {
  return (
    <RecordingPlayer recording={section} />
  ) 
}

return null
```

**Comment by zaptrem** [comment]
You’re right, sorry about that.

**Comment by zaptrem** [comment]
However, the issue with #269 still remains and makes this unusable in many cases. Do you have a fix in progress/workaround for this?
