### ISSUE TITLE
Performance Issue while using react navigation

### ISSUE THREAD

**Issue by Albert0405** [oblador/react-native-collapsible#297]
I notice a major performance issue while using react navigation with this lib. 
Im using createMaterialTopTabNavigator to display tabs on one of my app's screen. 
Collapsible works perfectly fine if its rendered inside the tabs (the JS stays from 50-60fps) but if it rendered outside the tabs for example in header, the JS drops to 20-40fps. 

You can watch it here for an accurate explanation
vid 1 - https://imgur.com/a/FnCs0Xb
vid 2 - https://imgur.com/VvSkLZ9

Note: I tested that in release mode to see if it just happens in debug mode, but it turns out it really is a bug or something

**Comment by iRoachie** [comment]
Thanks for the gifs! I looked at the issue as well and maybe we should consider rewriting the lib to me more performant. Thanks
