### ISSUE TITLE
Question on "collapsed property"

### ISSUE THREAD

**Issue by mekatron** [oblador/react-native-collapsible#3]
We are using react react-native-collapsible component.
We have several collapsible elements in the navigation page we are building.

In the beginning collapsed property is set to true. When one of the navigation elements is clicked, we are setting the collapsed property to false. This opens up ALL the navigation elements on the navigation page.

Is there any way we can restrict the opening of the sub-nav elements only to the nav elements we clicked on?

**Comment by oblador** [comment]
Hi, since the collapsed state is a controlled property you must have one state property for each `Collapsible`. You are probably better off using the [`Accordion`](https://github.com/oblador/react-native-collapsible#accordion-usage) component if you are using many collapsibles.

**Comment by jozan** [comment]
Slightly related: is is possible to have many `Collapsible`s open at the same time using `Accordion`?

I'm good without Accordion in this particular use case, just wondering.

:baby_chick:

**Comment by oblador** [comment]
@jozan: No not currently :-) I'm thinking maybe it would be preferable to have a `controlled` property to be able to avoid some boilerplate code in simple use cases.

**Comment by jozan** [comment]
Got it, thanks.

:baby_chick:
