### ISSUE TITLE
Type Error: Cannot convert undefined or null to an object Accordian.js:7

### ISSUE THREAD

**Issue by ziaulrehman40** [oblador/react-native-collapsible#304]
I have posted my question on [SO here](https://stackoverflow.com/questions/57704010/js-undefined-import-when-defining-global-constundefined-error).

But as it related directly to this specific package, i will ask it here as well. 

Issue arises [on this line](https://github.com/oblador/react-native-collapsible/blob/1be890e20897cb473c73ef7325eacea87ea3e175/Accordion.js#L67).

**All other details and my temporary solution are mentioned in SO question**, this issue might be related to my configuration. But as it is about this lib, i thought i will just post it here as well for anyone who may run into this in future.

Update: The workaround i have mentioned in my SO question seemed to be breaking again, don't know why. But further investigation suggests it might be presence of `babel-plugin-transform-react-remove-prop-types` in our project(under `babel-preset-react-app`).

**Comment by kyler-hyuna** [comment]
It's probably because proptypes are being stripped out when compiled for web.

**Comment by iRoachie** [comment]
It's probably because proptypes are being stripped out when compiled for web.

**Comment by ziaulrehman40** [comment]
I doubt that, if that was the case, moving this line from being a constant to local variable in function won't work either. Its something else.

**Comment by ziaulrehman40** [comment]
@iRoachie You were right, I am not quiet sure yet but this seems like the problem that props types are being stripped from production build.
As we are using `react-native-web` and `create-react-app` and `react-scripts` and all that. This issues arises only on web.

I am trying to figure out a way to not remove prop types from production builds with my setup. But as prop types were deprecated and [here is whole discussion on keeping it or removing it](https://github.com/facebook/create-react-app/issues/209), is it possible to just not use prop types any more?
Or at-least use them in a way that they are not needed in production builds?

This will make this library fully compatible with `react-native-web` which is whole new prospect IMO.

**Comment by scvgoe** [comment]
Any progress on this?

**Comment by oblador** [comment]
Fixed in 1.6.0
