### ISSUE TITLE
Content measure issue

### ISSUE THREAD

**Issue by AleksandrLeontev** [oblador/react-native-collapsible#313]
Why content is not remeasured after loading indicator is replaced with the content?

I think you need to update the height after changing child props in component.
If response comes after 1 second it works, if it is around 300ms it doesn't work, so I think the problem no in my component. Can you check the code example:

https://snack.expo.io/SJ84WiNtr

**Comment by Ashalbulk** [comment]
@AleksandrLeontev save my day!

**Comment by marioteik** [comment]
What did you do? @AleksandrLeontev
