### ISSUE TITLE
No ListView on Android

### ISSUE THREAD

**Issue by latusaki** [oblador/react-native-collapsible#32]
When using this library, passing a ListView to the accordion, on iOS it works as expected, although on Android, I get no scrolling. Any ideas what may be causing this? I have made sure that the ListView has flex:1, and its rowComponents as well.

**Comment by PreetiW** [comment]
I am facing the same problem.

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.
