### ISSUE TITLE
Accordion header closes  keybord when editing  TextInput 

### ISSUE THREAD

**Issue by ramisalem** [oblador/react-native-collapsible#337]
I have a TextInput on Accordion's header and can't continue typing on the keyboard, the keyboard closes immediately. 

[expo snack ](https://snack.expo.io/@ram50/accordin-input-issue)

**Comment by evo-sampath** [comment]
@ramisalem I am also facing this issue but I have TextInput in the renderContent, every time I type the textInput its keyboard is dismissing

did you found any solution for this?

**Comment by syedhaider02** [comment]
if you use a dynamic value as a key for mapping the collapsible component, React treats the new key as a new node, making the keyboard collapse.
