### ISSUE TITLE
Load content when accordion is pressed

### ISSUE THREAD

**Issue by nagibmahfuj** [oblador/react-native-collapsible#34]
Is it possible to show accordion content when it is pressed? I want to load some dynamic data on content. It seems its calling header and content every time when I press to any tab. Pls help @oblador

**Comment by phpjoe** [comment]
I have the same problem!

**Comment by oblador** [comment]
Currently no, the content needs to be rendered for the component to know the height. It would probably be possible with static content, but if you're loading it asynchronously that's a harder problem as the height will change, potentially mid animation.

**Comment by tioback** [comment]
Check #52

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.

**Comment by preetampatil3d** [comment]
Hi @iRoachie ,
I am facing same issue, i want to load dynamic content on header is pressed. can you please guide me how to do it.

Thanks in advance.

**Comment by iRoachie** [comment]
@preetampatil3d There's a PR #52 that supposedly fixed it but it needs some revisions. You can try using that fork and see if it works for you

**Comment by preetampatil3d** [comment]
Hi @iRoachie , Thanks for quick response. but #52 is about dynamic height. i am talking about content.
[https://stackoverflow.com/questions/45541989/best-accordion-for-react-native-for-dynamic-content](https://stackoverflow.com/questions/45541989/best-accordion-for-react-native-for-dynamic-content)

**Comment by iRoachie** [comment]
If i’m not mistaken that PR is about recalculating the height of the collapsible with when the height of the content changes.
