### ISSUE TITLE
Not working with react-native-web 0.12.2

### ISSUE THREAD

**Issue by altany** [oblador/react-native-collapsible#341]
React Native 0.61.5
Trying to upgrade react-native-web version to latest and I get this error when running the webapp.
![image](https://user-images.githubusercontent.com/5974044/77320186-c92c7c80-6d18-11ea-8ccb-932c52d1af8c.png)

**Comment by walidvb** [comment]
Same here. @altany were you able to address this?

**Comment by altany** [comment]
Not while using this library. We actually created our own according component.

**Comment by oblador** [comment]
Fixed in 1.6.0
