### ISSUE TITLE
How can I collapse it programmatically ?

### ISSUE THREAD

**Issue by nandantal** [oblador/react-native-collapsible#353]
I want to collapse it on click of a button. Is there any way to do it ?

One way is by changing the active sections. Is there any other way ?

**Comment by henrykuzmick** [comment]
You can just change the `collapsed` prop on button click.

```
const [isCollapsed, setCollapsed] = useState(false)
```

```
<SomeButton onPress={() => setCollapsed(true)}>
    <Text>Press me</Text>
</SomeButton>
```

```
<Collapsible collapsed={isCollapsed}>
    <SomeContent />
</Collapsible>
```

**Comment by wmonecke** [comment]
@nandantal Could you please close this issue? :)
