### ISSUE TITLE
Background Image in Header

### ISSUE THREAD

**Issue by gHashTag** [oblador/react-native-collapsible#37]
Trying to make the image file header accordion adaptive on all platforms, it is impossible. 
What's the matter?
![simulator screen shot 24 2016 20 24 35](https://cloud.githubusercontent.com/assets/6774813/16345263/19d4d19e-3a52-11e6-992c-4f88ee5e4205.png)

``` javascript
<Image style={styles.header} source={section.pic}><Text style={styles.headerText}>{section.title}</Text></Image>
```

StyleSheet:

``` javascript
const styles = StyleSheet.create({
  header: {
    flex: 1,
    padding: 30,
    alignItems: 'stretch'
  },
  headerText: {
    textAlign: 'center',
    fontSize: 30,
    alignItems: 'center',
    color: '#f9f6fb',
    fontWeight: '200'
  },
  content: {
    paddingTop: 30,
    backgroundColor: '#fff',
  },
  textContent: {
    paddingTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
    paddingBottom: 10
  }
});
```

The complete code here:
https://github.com/gHashTag/iSoulClub/blob/master/index.ios.js

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.
