### ISSUE TITLE
How to make a submenu?

### ISSUE THREAD

**Issue by gHashTag** [oblador/react-native-collapsible#38]
How to make a submenu(subHeader) and suSubMenu?

**Comment by oblador** [comment]
Did you try nesting `Accordion`s?

**Comment by gHashTag** [comment]
Differently tried, you can set an example?

**Comment by oblador** [comment]
Unfortunately I don't have the time to write you an example. If you post the code you are failing with I could try and see if I can spot any errors.

**Comment by gHashTag** [comment]
Menu:
https://gist.github.com/gHashTag/148e9a5e26b76ce793678c85c0b47d92
Submenu:
https://gist.github.com/gHashTag/b6b17c464fc2d0ed077fa6d3cfa14ccc
![simulator screen shot 16 2016 15 00 43](https://cloud.githubusercontent.com/assets/6774813/17698253/052511bc-63cb-11e6-8611-f846910c662a.png)
____
Now when you click on a menu, the menu offers everything, and that I would need to work both in turn.

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.
