### ISSUE TITLE
Flexbox limitation - unexpected behaviour 

### ISSUE THREAD

**Issue by JakobReiter** [oblador/react-native-collapsible#41]
Great Plugin. Love it. But I found a big bug!
I am using the `<Accordion>` to swap 2/3 of the page. There should be a 1/3 fixed Action Footer.

My problem is that if I assign a (pixel) height via `StyleSheet` to the accordion it works properly.
When I assign `flex: 1` to the accordion then the collapsable will no longer appear.
When nothing is assigned then the accordion is only the required height, but is not filling the space (which I think is the expected behaviour). 
Within the `_renderContent` I am using a `ScrollView` in case the content gets too long, which is the point I guess of an accordion.

The code looks very similar to this:

``` js
<View style={flex: 1}>
    <View style={flex: 2}>
         <Accordion
              sections={['Section 1', 'Section 2', 'Section 3']}
              renderHeader={this._renderHeader.bind(this)}
              renderContent={this._renderContent.bind(this)}
              style={flex: 1} /* <- THIS DOES NOT WORK, 
                              {height: 200} will work, but is not responsive
                              */ 
         />
     <View style={flex: 1, backgroundColor: 'gray'}>
           <Text>Action Footer</Text>
     </View>
</View>
```

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.
