### ISSUE TITLE
leave the content open

### ISSUE THREAD

**Issue by ronnpang1** [oblador/react-native-collapsible#42]
Is there anyone to just leave the content and header open? For example if the user clicks on the header, it remains open until the user chooses to close it rather than it disappearing when another header is clicked on?

**Comment by oblador** [comment]
Just use multiple `Collapsible`.

**Comment by blazeprasanna** [comment]
@oblador Kindly Explain how to use multiple collapsible. Please describe

**Comment by ronnpang1** [comment]
@blazeprasanna I managed to solve it by creating a component that had the collapsible and then apply a mapping function to create multiple instances of the collapsible panel. This way, each collapsible maintains its own state. For instance, you would have:

var itemfeed = this.state.jsonData.map((item,i) => {

<panel key={i}></panel>
}

where panel is some component where you actually create or implement the collapsible panel.

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.
