### ISSUE TITLE
How to handle dynamic accordion content

### ISSUE THREAD

**Issue by Burak07** [oblador/react-native-collapsible#43]
Thanks for this useful component,

I'm having a trouble while trying to create an accordion.

When user clicks a submenu under a menu, content of the accordion is changed and it is rerendered with a different content. 

This is how i use activeSection in accordion
  activeSection={this.state.activeSection}
In my header content every view's structure is 

View
View (image)
 View (text)
 View (image)
View 

assuming that if i have 4 rows in old content and i click 2nd item which is index 1 in new content 2nd head (index1)view's text is changed but images are not changed. I'm having this issue only with iOS. Code works well with Android images are changed properly.

note: images's sources and logs controlled several times.

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.
