### ISSUE TITLE
[Accordion][RN29][iOS] ListView in active Collapsible content would not show up until get swiped

### ISSUE THREAD

**Issue by JaxGit** [oblador/react-native-collapsible#45]
Just record here to help others. 
If you render a ListView in renderContent(content, idx, isActive){} for `<Accordion />` , even if you have clicked the header to activate the Collapsible section and render the section with correct contentHeight, the ListView is invisible unless you swipe vertically or horizontally. 

removeClippedSubviews={false} needs to be applied to ListView to prevent this. 

Refs: 
[Fixed removeClippedSubviews](https://github.com/facebook/react-native/commit/1048e5d3445094393298d4e818ff04c41f4e56a7#commitcomment-18152298)
[ListView (or perhaps ScrollView) disappears after running in background for several minutes](https://github.com/facebook/react-native/issues/8607)

**Comment by oblador** [comment]
Is this actionable from my side or should we close it and just keep it in the archive for reference?

**Comment by waleedarshad-vf** [comment]
I am having same problem. Listview is getting load after few seconds

**Comment by edencakir** [comment]
I'm having the same problem. removeClippedSubviews={false} solved my problem. @JaxGit Thanks!

**Comment by pr-rojan** [comment]
@JaxGit Could you please share your code to render ListView in renderContent?

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.
