### ISSUE TITLE
How to make Accordion/Collapsible to take all available height

### ISSUE THREAD

**Issue by veedeo** [oblador/react-native-collapsible#46]
I would like to put a ScrollView inside a collapsible/accordion, so when expanded it will take all available space.
It works only when I specify exect height, so I got a height from onLayout of Accordion's parent and put it to Accordion style height. but then this height sent direclty to inner collapsible without calculating accordion headers.
What Im doing wrong?

**Comment by tioback** [comment]
Check #52

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.
