### ISSUE TITLE
Accordion content blinking 

### ISSUE THREAD

**Issue by meghvarse** [oblador/react-native-collapsible#473]
Facing blink issue while open accordion content from header.

https://github.com/oblador/react-native-collapsible/assets/140066955/45284153-c656-41a5-91f1-405122f4fc13

Facing this with RN new architecture.

**Comment by maestrolsj** [comment]
reproducable

**Comment by dioi2000** [comment]
same

**Comment by dioi2000** [comment]
@meghvars
try this
renderChildrenCollapsed={section.length < 1}

**Comment by oblador** [comment]
Fixed in [1.6.2](https://github.com/oblador/react-native-collapsible/releases/tag/v1.6.2)
