### ISSUE TITLE
Unmeet peer dependency

### ISSUE THREAD

**Issue by waleedarshad-vf** [oblador/react-native-collapsible#48]
UNMET PEER DEPENDENCY react@15.3.1
└── react-native-collapsible@0.7.0 

**react-native version**
react-native-cli: 1.0.0
react-native: 0.27.2

**Package.json**
  "dependencies": {
    "@remobile/react-native-action-sheet": "^1.0.1",
    "alt": "^0.18.5",
    "lodash": "^3.10.0",
    "react": "^15.1.0",
    "react-native": "0.27.2",
    "react-native-android-share": "0.0.4",
    "react-native-bottom-sheet": "^0.1.1",
    "react-native-button": "^1.6.0",
    "react-native-collapsible": "^0.7.0",
    "react-native-custom-action-sheet": "0.0.11",
    "react-native-drawer": "^2.2.3",
    "react-native-gifted-spinner": "0.0.4",
    "react-native-lazyload": "^1.1.0",
    "react-native-parallax-scroll-view": "^0.19.0",
    "react-native-scrollable-tab-view": "^0.5.4",
    "react-native-scrollview-lazyload": "^1.0.5",
    "react-native-share": "^1.0.13",
    "react-native-storage": "^0.1.2",
    "react-native-swiper2": "^2.0.7",
    "react-native-viewpager": "^0.2.11",
    "superagent": "^2.1.0"
  }

**Comment by waleedarshad-vf** [comment]
0.27.2 require react version of 15.1.0. so changing version does not work. any help would be appreciated.

**Comment by oblador** [comment]
It's unrelated to this module as it has no peerDependendencies.

**Comment by waleedarshad-vf** [comment]
I am newbie so does not understand. what it means. do i can use it safely ignoring this?

**Comment by waleedarshad-vf** [comment]
What i have to do exactly ?

**Comment by oblador** [comment]
The example project is using 
```
"react": "^15.1.0",
"react-native": "^0.28.0",
```

so you can safely use this component in your project.

**Comment by waleedarshad-vf** [comment]
Thanks
