### ISSUE TITLE
Expanding elements

### ISSUE THREAD

**Issue by johnnyjanzen** [oblador/react-native-collapsible#5]
On our project we are using the collapsible to create an expandable pop-down comments section under boxes of content.  Is there a way to ensure that the uncollapsed content pushes other items out of it's way?  Perhaps this is out of the scope of the "collapsible" component - just thought I'd double check here.  For example: the first screenshot represents the collapsed view.  The second screenshot is the uncollapsed view.  The red box represents the uncollapsed content: note that it is being displayed BEHIND the following item box.
![screen shot 2015-08-24 at 3 20 44 pm](https://cloud.githubusercontent.com/assets/9919877/9454062/1b350aaa-4a74-11e5-8c2d-7ab2f9fa82d5.jpg)
![screen shot 2015-08-24 at 3 20 58 pm](https://cloud.githubusercontent.com/assets/9919877/9454064/1e3c4362-4a74-11e5-9338-1200b71be6a7.jpg)

Appreciate your time and the resource you have built for the community!  Peace.

**Comment by oblador** [comment]
Hi @johnnyjanzen, 

I'm pretty sure that's a bug in your stylesheet somehow, since it works well in the demo project for example. Do you have a fixed height, use absolute positioning or something like that?

If not please post a minimal reproducible example of the bug so I can examine it.

**Comment by johnnyjanzen** [comment]
You're absolutely right!  Having a fixed height (ie. "height: 390") was the problem.  Cheer's!
