### ISSUE TITLE
Auto Collapse when select another item in list

### ISSUE THREAD

**Issue by rainbowhat** [oblador/react-native-collapsible#50]
<Accordion
          header={header}
          content={content}
          easing="easeOutCubic"
        />

How do I make it work like in Demo where it would automatically collapse when another item is being selected.

**Comment by frevib** [comment]
This is done by default like in the demo. Can you show you code?

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.

**Comment by ManigandanRaamanathan** [comment]
@iRoachie  Any update on this issue? I'm facing trouble in getting started with this  part

**Comment by iRoachie** [comment]
Is there any reason you don't use the Accordion? It does this by default

**Comment by ManigandanRaamanathan** [comment]
@iRoachie  I'm trying to get the accordion for within the dynamic data of FlatList. By default this library requires us to key in the variable to collapse and uncollapse the accordion. But if I add this in the dynamic data, then I won't be able to assign a specific variable to collapse the data whenever user press the accordion of dynamic data. Is there a way to automatically collapse when ever user press the accordion?

**Comment by iRoachie** [comment]
Hey @ManigandanRaamanathan let's talk about this on a new issue. Also if you can replicate your flatlist + accordion setup on https://snack.expo.io, then we can look at it.
