### ISSUE TITLE
Open a section programmatically

### ISSUE THREAD

**Issue by edencakir** [oblador/react-native-collapsible#55]
Is it possible to open/close - toggle a section? It would be nice to have it.

**Comment by edencakir** [comment]
Fool me, using states at _activeSection_ prob can toggle a section.

**Comment by oblador** [comment]
If you want to move control over active section to your own component, you must implement the `onChange` prop to make header taps work. See the example project for usage.

**Comment by edencakir** [comment]
I'll give it a shot. Thanks for the reply.
