### ISSUE TITLE
Calendar Inside collapsible

### ISSUE THREAD

**Issue by basequatro** [oblador/react-native-collapsible#57]
Calendar is not showing inside collapsible.
Only shows after swiping the calendar component.

**Comment by SudoPlz** [comment]
This might have to do with the calendars `ScrollView` component using `removeClippedSubviews`. 
You might wan't to manually turn that off by doing: `removeClippedSubviews={false}`

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.

**Comment by michelarteta** [comment]
removeClippedSubviews={false} works very well for me. Thanks!
