### ISSUE TITLE
Can't open the panel which is be collapsed if has not set height style to Collapsible

### ISSUE THREAD

**Issue by susan-github** [oblador/react-native-collapsible#61]
RN Version: 0.38.0
collapsible Version: 0.7.0
If I haven't set height or minHeight style to Collapsible, the collapsed panel can't be opened.
```
<Button
  onPress={this.togglePanel}
  title="切换Panel"
/>
<Collapsible collapsed={this.state.isCollapsed} style={{ minHeight: 100 }}>
  <Text>我是面板</Text>
</Collapsible>
```
```
togglePanel() {
  this.setState({ isCollapsed: !this.state.isCollapsed })
}
```

**Comment by wootwoot1234** [comment]
Thanks @susan-github !  I was having the same issue but didn't know how to fix it till I saw this!  I'm running the latest React Native.  Adding ```style={{ minHeight: 100 }}``` to the ```<Collapsible/>``` element seems to fix it.

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.
