### ISSUE TITLE
Allow each Collapsible to open/close individually independent from other Collapsibles

### ISSUE THREAD

**Issue by dmitriybrakk** [oblador/react-native-collapsible#63]
`	renderSections(sections){
				return(
					sections.map(function(section, i){
							return (
								<View>
								<TouchableHighlight onPress={???}>
									<View style={styles.header}>
										<Text style={styles.headerText}>{section.chapter}</Text>
									</View>
								</TouchableHighlight>
								<Collapsible collapsed={this.state.collapsed} align="center">
									<View style={styles.content}>
										<HTMLView value={section.text} stylesheet={styles}
											onLinkPress={(url) => this.getDetailsFromLink(url)}/>
									</View>
								</Collapsible>
								</View>
							)
					}.bind(this))
				)
	}`

**Comment by sibelius** [comment]
could u please format ur code? and give more information?

**Comment by dmitriybrakk** [comment]
There are multiple Collapsible components that render dynamic content, they are all open at once when the screen is rendered. I want each of them be able to open and close independently of each other. For example, i have overview section and short description section. So, i want to collapse overview while leaving shot description open. How could i approach that? 

```javascript
renderSections(sections){ 
   return( sections.map(function(section, i){ 
       return ( 
          <View> 
            <TouchableHighlight onPress={???}> 
              <View style={styles.header}><Text style={styles.headerText}>{section.chapter}</Text> </View>              
            </TouchableHighlight> 
            <Collapsible collapsed={this.state.collapsed} align="center">
              <View style={styles.content}>
               <HTMLView value={section.text} stylesheet={styles} 
                  onLinkPress={(url) => this.getDetailsFromLink(url)}/>
              </View> 
            </Collapsible>
          </View> 
       ) }.bind(this)) ) }
```

**Comment by joypatel04** [comment]
@dmitriybrakk Instead of using .map function you can render separately using ListView and it goes to renderRow so every section will render separately and open close separately.

**Comment by iRoachie** [comment]
Hey, this issue has been inactive for long time and will be closed. If the issue still persists feel free to tag me to reopen.

**Comment by ManigandanRaamanathan** [comment]
@joypatel04  Please provide example
