### ISSUE TITLE
Broken for 0.40.0?

### ISSUE THREAD

**Issue by robcalcroft** [oblador/react-native-collapsible#68]
Does this work on latest RN release? Doesn't render for me

**Comment by ominiverdi** [comment]
me using react-native-collapsible/Accordion, as soon as update to 0.40 I can see the titles of the Accordion. Clicking on the titles changes the icon for expansion/compression but no contents shows anymore.
Anything I can do to help fix this?

**Comment by ms88privat** [comment]
I upgraded from 0.22.0 to 41-rc and it is also broken for me (after fixing a lot of other things...)

**Comment by JUnderwood1991** [comment]
Agreed that it's broken for latest release.

**Comment by ms88privat** [comment]
see https://github.com/oblador/react-native-collapsible/pull/69

**Comment by oblador** [comment]
AFAIK this should be fixed a few days ago in yoga master, hopefully that will make it into the next release of RN.

**Comment by Naoto-Ida** [comment]
+1

**Comment by Kurt57** [comment]
@oblador  new infos that the fix will be definitively in the next react-native version ? 

and do anyone know when the new react-native version will arrive....

**Comment by Naoto-Ida** [comment]
@Kurt57 Didn't they say that they're slowing down the updates to once per month? I'm guessing it'll be sometime this week, considering 0.40.0 came out about 25 days ago.

**Comment by Kurt57** [comment]
with the fix for this module? @Naoto-Ida

**Comment by Naoto-Ida** [comment]
@Kurt57 Not sure, I guess we'll have to wait for 0.41.0 and see.

**Comment by davingreen** [comment]
I'm really desperate to get this working today. I've tried rolling back RN to 0.39.2, but still no expanding on iOS. Unfortunately, this is an urgent bug fix, so I can't wait for the next release of RN. Can anyone who has solved this by "building from the source" point me in the right direction for getting the collapsibles working on iOS?
Note, it works fine on Android (0.39.2 and 0.40.0)
So far, I've tried:

- Upgrading to 0.40.0 and adding 'scroll' to Collapsible.js ln99.
- Downgrading to 0.39.2. Also tried added 'scroll'
- Downloading RN repo master branch and replacing 'react-native' folder in node_modules, then run npm install inside the repo. Gives a lot of error: 'React/RCTwhatever.h' file not found .

**Comment by ammichael** [comment]
@davingreen Incredible how it is working on Android. Mine didn't work from RN 0.37 up. I needed to downgrade to RN 0.36.

**Comment by davingreen** [comment]
@ammichael Thanks for the response. I tried a completely new RN project with:
`react-native init Project --version react-native@0.36.0`
But I'm still not getting the expansion of sections. Can you shed some more light on how you rolled back to 0.36.0 and if you did anything else to get it working?

**Comment by ammichael** [comment]
@davingreen Actually I just downgrade using npm, both react and react-native. Something like:

```
npm install --save react@15.3.2
npm install --save react-native@0.36
```

Then I restarted the packager and worked fine..

**Comment by davingreen** [comment]
Reading through #51 , it seems like we keep waiting for a fix with each new RN release, but the last several have not had it. 

@ammichael Downgrading didn't work. 😦  But I downgraded and then used this fork: git://github.com/relayfoods/react-native-collapsible.git#collapsible-not-expanding-temp-fix. Finally got it to work.. 

If anyone has an approach that doesn't require downgrading RN, please share!

**Comment by oblador** [comment]
Hey guys, try [0.8.0](https://github.com/oblador/react-native-collapsible/releases/tag/v0.8.0) together with the just released React Native 0.41.0

**Comment by Naoto-Ida** [comment]
@oblador does it work? I'm on 0.41.0 so I can test it if you haven't yet.

**Comment by oblador** [comment]
I've tested the Example project and it works, but please do test it.

**Comment by bhses** [comment]
it works for me! 👍

**Comment by ammichael** [comment]
Works for me too. Nice! (:
