### ISSUE TITLE
renderSeparator a la ListView?

### ISSUE THREAD

**Issue by npapanastasiou** [oblador/react-native-collapsible#7]
Does there exist a way of adding a separator to Accordion as one would with ListView (rendered below the contents of renderContent)? If there is no such feature, is there a workaround or plans to add it?

Also, this library's been a life saver, so thanks for developing it!

**Comment by oblador** [comment]
Hi @npapanastasiou, 

Easiest way is to add a `borderTop` to each header and a `borderBottom` to the accordion element.

**Comment by npapanastasiou** [comment]
Perfect, thanks!
