### ISSUE TITLE
Collapsible not working.

### ISSUE THREAD

**Issue by jefferyvincent** [oblador/react-native-collapsible#71]
It appears that the Collapsible View is not working in ios. I've tried updating to the latest version ("react-native-collapsible": "^0.8.0") and I am still having issues. 

Seems this remains hidden regardless.

```
<Collapsible collapsed={false}>
      <Text> Yo </Text>
</Collapsible>
```

**Comment by oblador** [comment]
Are you on React Native 0.41?

**Comment by jefferyvincent** [comment]
No 0.40.0.

**Comment by jefferyvincent** [comment]
Works!!!! :) Thanks
