### ISSUE TITLE
Can anyone help provide a typescript declaration for this react native library?

### ISSUE THREAD

**Issue by kccheung** [oblador/react-native-collapsible#74]
I am struggling in making the declaration for my project which uses typescript. I have tried using below:

    declare module "react-native-collapsible" {
        import React, { ReactNode, Component, ComponentClass, PropTypes } from 'react';
        import { ViewStyle } from 'react-native';

        namespace RNA {
            export interface IAccordionProperties extends React.Props<AccordionStatic> {
                sections?: Array<any>,
                renderHeader?: Function,
                renderContent?: Function,
                onChange?: Function,
                align?: 'top' | 'center' | 'bottom',
                duration?: number,
                easing?: string,
                initiallyActiveSection?: number,
                activeSection?: boolean | number,
                underlayColor?: string,
            }

            export interface IAccordionState {
                activeSection?: boolean | number,
            }

            interface AccordionStatic extends ComponentClass<IAccordionProperties> {
                // TODO: function(s) to be exposed
            }

            export var Accordion: AccordionStatic;
            type Accordion = AccordionStatic;
        }

        export = RNA;
    }

But I still cannot make the Accordion appear properly.

**Comment by iRoachie** [comment]
@kccheung Will take a look at it

**Comment by iRoachie** [comment]
@kccheung I finished the definitions, they're on DefinitelyTyped. To use them, just run
npm - `npm install -D @types/react-native-collapsible` 
yarn - `yarn add --dev @types/react-native-collapsible`
