### ISSUE TITLE
How can I make a react native expanding cells scrollview in IOS which like the below example?

### ISSUE THREAD

**Issue by keung725** [oblador/react-native-collapsible#76]
How can I make a react native expanding cells scrollview in IOS which like the below example?

[https://www.raywenderlich.com/99087/swift-expanding-cells-ios-collection-viewsexample](url)

I have tried a long time to calculate manually but the performance is bad. And I have done a research a long time, seems there are no any third party library to do it.

Would anyone can help me? Thanks.

**Comment by iRoachie** [comment]
@keung725 Your link is broken

**Comment by mtzluisalfredo** [comment]
How can I make a react native expanding cells scrollview in IOS which like the below example?
https://www.raywenderlich.com/99087/swift-expanding-cells-ios-collection-views

¿Alguien podría ayudarme? Gracias.

**Comment by iRoachie** [comment]
Closing this as outside the scope of this project. Look into ScrollView listeners and use the Animated api to achieve this effect.
