### ISSUE TITLE
activeHeaderStyle

### ISSUE THREAD

**Issue by bradynapier** [oblador/react-native-collapsible#8]
Hey Oblador,
  As discussed on Discord, would be cool to have an option for "activeHeaderStyle" on the Accordion.  This would allow a separate style to be applied internally when an item is opened.

  Extra credit for adding a transition to it.  Would be cool if it animated for example if you change background color - but i have never done all that yet so not sure how complex that gets!

  Thanks for the package!

**Comment by oblador** [comment]
Decided `activeHeaderStyle` was the wrong way to do it, so instead the `render*` functions now get a third `isActive` argument. Together with the `Animatable` library it's now easy to change backgrounds or animate stuff, example here: https://github.com/oblador/react-native-collapsible#transition-backgrounds
