### ISSUE TITLE
Nested collapsibles

### ISSUE THREAD

**Issue by JeffreyLeeSpokeo** [oblador/react-native-collapsible#85]
I have an issue where my inner collapsible collapses, but the outer one does not scale. My code structure looks like this:

```
<View>
    <Collapsible>
        <InnerComponentWithCollapsible>
        </InnerComponentWithCollapsible>
    </Collapsible>
</View>
```

Does collapsible not support this or is there possibly something wrong with my code? When I change the outer collapsible into a view, my container expands properly. Also when I just simply get rid of the outside collapsible

**Comment by GenericJam** [comment]
I had this same issue. It took me a long time to figure out it was Collapsible that was responsible.

**Comment by iRoachie** [comment]
@oblador Can you confirm this behaviour?

**Comment by travisday** [comment]
Any new info on this looking to do a similar thing where I can infinitely add collapsible lists @iRoachie @oblador also not seeing much activity on this repo should I consider just writing my own  collapsing feature?

**Comment by iRoachie** [comment]
@travisday Here's an example using nested collapsibles that work just fine. https://snack.expo.io/BkpT9Zhpb.

**Comment by travisday** [comment]
@iRoachie Thanks! Works great

**Comment by archvill** [comment]
I've also had issues with height not increasing in outer collapsible when expanding inner one (a simple menu-like tree). The single change I've made is downgrade lib to 0.9.0, as I not found any significant differencies with example from @iRoachie. Looks like newer versions doesn't support it well.

**Comment by iRoachie** [comment]
Yea you're correct, it has to rollback. See https://github.com/oblador/react-native-collapsible/pull/197
