### ISSUE TITLE
Open a tab by default

### ISSUE THREAD

**Issue by brlrb** [oblador/react-native-collapsible#89]
How can we set an Index so that some tab are open by default. Currently everything is collapsed. For example, we can have index[4] set to open when the app loads or when calling the accordion component.

**Comment by aarontrank** [comment]
See this pull request I submitted.  Modify your code as such:  https://github.com/oblador/react-native-collapsible/pull/81

**Comment by iRoachie** [comment]
Hey @brlrb this behavior is already accomplished using the `initiallyActiveSection` prop.

Here's an example snack showing this. https://snack.expo.io/HJVVrWOQf
