### ISSUE TITLE
Animated On Open but Not Close?

### ISSUE THREAD

**Issue by bradynapier** [oblador/react-native-collapsible#9]
Some content animates nicely when it opens.  For example, I have an icon that is set to center vertically so when the content opens it slides nicely down to stay center.  However when closing the collapsible container it jumps to the top immediately rather than animating.  Any way to resolve?

Also any way to have size also animate?  So if an icon or text were to get larger it would automatically show it animate as it gets larger?  Think that may require your Animatable

**Comment by oblador** [comment]
Can you post example code for me to review?

If you want to animate sizes etc then the animatable library can be used alone or together with this component :-)

**Comment by bradynapier** [comment]
it's a bit hard since my styles are dynamic but here

     <View style={{flex: 1, alignSelf: 'center'}}>
	  {this.renderIcon(itemIcon, iconStyle, iconImage)}
	 </View>
	<View style={[{flex: 5, alignSelf: 'center'}, eventContainer]}>
	  <View style={{flex: 1, flexDirection: 'column'}}>
	    <Text style={styles.this.eventTitle}>{title}</Text>
	    <Text allowFontScaling={true} style={styles.this.timestamp}>{date} at {time}</Text>
	    <Collapsible style={{flex: 1, width: VP.vw(90)}} collapsed={this.state.isCollapsed}>
	      <Text allowFontScaling={true} style={[styles.type.white, {flex: 1}]}>{subject}</Text>
	    </Collapsible>
	  </View>
	</View>

**Comment by bradynapier** [comment]
![image](https://cloud.githubusercontent.com/assets/8041420/10749062/7e7ac1f0-7c23-11e5-9abc-51209765aaf5.png)

![image](https://cloud.githubusercontent.com/assets/8041420/10749069/8630032e-7c23-11e5-989c-87ed9970be04.png)


So in the images above the icon nicely slides down as the container opens but when it closes it shoots to the top immediately then the animation begins.

**Comment by oblador** [comment]
Sorry but that references alot of variables and functions not available in your example. Please try to make a minimal reproducible example :-)

**Comment by bradynapier** [comment]
User Error :-P thanks!

**Comment by ggepenyan** [comment]
In my case, I just used `<Collapsible collapsed={isCollapsed}>` but closing animation didn't work. I have tested in android.

**Comment by iRoachie** [comment]
@ggepenyan Can you open a new issue?

**Comment by nsdub** [comment]
The issue @ggepenyan opened for reference: https://github.com/oblador/react-native-collapsible/issues/185
