### ISSUE TITLE
content disappear sometimes when click to expand 

### ISSUE THREAD

**Issue by kennedy0527** [oblador/react-native-collapsible#90]
![issue in action](https://thumbs.gfycat.com/ThoroughWanAnura-size_restricted.gif)

I just discover that if I keep clicking to expand accordion, then content will sometimes disappear

how to fix that? 

my data structure is like below 
```javascript
var a = [{
  title: 'a'
}, {
  title: 'b',
  subMenu: [{
    title: 'b0',
    content: '123'
  },{
    title: 'b1',
    content: '123'
  }]
}]
```
```html
<Accordion
   sections={a}
   renderHeader={this._renderHeader}
   renderContent={this._renderContent}
/>
```
and render method

```javascript
_renderHeader = (section, index, isActive) => {
  if(section.subMenu){
    return (
      <View>
        <Text>
          {section.title}
        </Text>
      </View>
    );
  }
  return (
    <TouchableOpacity
      delayPressIn={0}
      onPress={}
    >
      <View>
        <Text>
          {section.title}
        </Text>
      </View>
    </TouchableOpacity>
  );
}
_renderContent = (section, index) => {
  if(section.subMenu){
    return section.subMenu.map((k, i) => {
      return (
        <TouchableOpacity
          delayPressIn={0}
          onPress={}
        >
          <View>
            <Text>
              {k.content}
            </Text>
          </View>
        </TouchableOpacity>
      );
    })
  }
  return;
}
```

maybe the issue is caused by my usage ?!

if I'm wrong please recommend me some better usages

thanks

**Comment by arcollector** [comment]
flex: 1 in renderContent main wrapper

**Comment by kennedy0527** [comment]
![issue](https://media.giphy.com/media/l1BgT72cBeURETnuU/giphy.gif)

**Comment by kennedy0527** [comment]
thanks @arcollector 
add `flex: 1` into renderContent main wrapper fix the problem

but it cause another problem ...

![](https://thumbs.gfycat.com/ReasonableVibrantArizonaalligatorlizard-size_restricted.gif)

click button then its text will disappear

and re-expand it will become normal again...

I have set text style to static fontSize and `flex:1` still doesn't work

btw it's normal if I don't add `flex: 1` to renderContent main wrapper

**Comment by arcollector** [comment]
dont put a view inside a touchable
also, in render content wrap the entire output inside a view

**Comment by kennedy0527** [comment]
@arcollector thanks for reply

I've changed _renderContent wrapper like below
```javascript
if(section.subMenu){
  return (
    <View style={{flex: 1}}>
      {
        section.subMenu.map((k, i) => {
          return (
            <TouchableOpacity
              key={i}
              delayPressIn={0}
              onPress={}
            >
              <View>
                <Text>
                  {k.content}
                </Text>
              </View>
            </TouchableOpacity>
          );
        })
      }
    </View>
  )
}
return null;
```
I give every button  `padding: 16`
and subbutton `paddingLeft: 32` (top, bottom, right is still 16)

and after I pressed button, its height will be calculated wrong (others are also wrong)

as you can see below gif

![issue](https://thumbs.gfycat.com/EnlightenedSmoggyImperialeagle-size_restricted.gif)

and after I pressed every button in sublist, it back to normal again .....

**Comment by arcollector** [comment]
no idea mate,, try removing the view elem inside each touchable
also, try setting lineHeight at each text elem, and see what ocurrs

**Comment by kennedy0527** [comment]
@arcollector I just discovered that the problem is on the `<Text> `

I changed text color like below
```javascript 
const color = focused ? '#1abc9c' : '#fff';

<Text style={{ color }} > ... </Text>
```
but If I don't change it, it will become normal...
```javascript
<Text style={{ color: 'white' }} > ... </Text>
```

![s](https://thumbs.gfycat.com/FlatImperturbableArabianwildcat-size_restricted.gif)

what a weird problem...

**Comment by kennedy0527** [comment]
I fix this by setting static height to `TouchableOpacity ` not its inner `View`
```javascript
<TouchableOpacity
  style={{ flex: 0, hight: 47.5 }}
  key={i}
  delayPressIn={0}
  onPress={}
  >
  <View>
    <Text>
      {k.content}
    </Text>
  </View>
</TouchableOpacity>
```

**Comment by pavelPX** [comment]
Hi! 
I've removed "flex: 1" property and added "flexBasis: '100%'" and everything works fine for me.
