### ISSUE TITLE
Does the Accordion work with a Touchable Highlight in the renderHeader and renderContent arguments

### ISSUE THREAD

**Issue by rrajasek92** [oblador/react-native-collapsible#92]
Can't seem to get this working. For example: 

```
<Accordion
sections={SECTIONS}
renderHeader={() =>{
  return (
    <View>
    <TouchableHighlight style={{padding: 5}}
    underlayColor = '#191970'
    >
    
    <View style = {styles2.row}>
    <Text style = {{color:'#B67075'}}>Hello</Text>
    </View>
    
    </TouchableHighlight>
    </View>
  );
}}
renderContent={() =>{
  return (
    <View>
    <TouchableHighlight style={{padding: 5}}
    underlayColor = '#191970'
    >
    
    <View style = {styles2.row}>
    <Text style = {{color:'#B67075'}}>Hello</Text>
    </View>
    
    </TouchableHighlight>
    </View>
  );
}}
/>
```

**Comment by kiritmodi2702** [comment]
yes, I have also same problem. its not working TouchableHighlight and TouchableOpacity doesn't working inside the renderHeader and renderContent,

**Comment by rdoyle975** [comment]
Same problem here, I need to call a function onPress and I always got the same error _this3._onPressButton is not a function

**Comment by ashusdn** [comment]
Same Problem here, when trying to use on press method inside renderHeader, can anyone have implemented same.
 _renderHeader(section, i, isActive) {
        return (
 <View style={styles.headerRowStyle}>
                    <Image style={styles.carretImageStyle} source={isActive ? caretDown : caret} />
                    <Text style={styles.headerText}>{section.title}</Text>
                    <TouchableOpacity  onPress={() => onUnitItemClick(section.title)}   underlayColor="transparent">
                        <Image source={arrow} style={{ transform: [{ scaleX: I18nManager.isRTL ? -1 : 1 }], alignItems: 'flex-end', }} />
                    </TouchableOpacity>
                </View>
  );
    }

**Comment by iRoachie** [comment]
Hey sorry for late reply. Can any of you make an example over here https://snack.expo.io. Just so I can see what code produces the error.

**Comment by iRoachie** [comment]
Closing as inactive. Please ping me to reopen or create a new issue if this still occurs in the latest version
