### ISSUE TITLE
Collapsible closing without modifying the props.

### ISSUE THREAD

**Issue by tiaaaa123** [oblador/react-native-collapsible#95]
Hi! 
I'm having issue with the Collapsible component.

As you can see in this [gif](https://gyazo.com/14eabb4a1d34c887f8a5a6bd47341585), the Collapsible close, but the props doesn't change. When I press on the button to show/hide the collapsible, it change the props value to close (But it doesn't change in the app because it already collapsed!). On the second click, the Collapsible is back open.

Got an explaination/solution/fix?
Thanks!

```
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
"react-native-collapsible": "0.8.0",
```

EDIT: issue on iOS only

**Comment by iRoachie** [comment]
Hey @tiaaaa123 can you set up a simple example on https://snack.expo.io/ ? Just so we can see the behaviour and the code that produces it

**Comment by antoxann96** [comment]
@tiaaaa123 Have you fixed this issue? I have the same(

**Comment by Louis-T** [comment]
Hi !
I have almost the same issue.
I'm trying to set up the accordion with stateful TextInput inside, and the accordion's content is disappearing when I try to modify the TextInput value.

I have set up a small repo for you to test : https://github.com/Louis-T/collapsible-bug

This is just a small repo that I created using `react-native init`. And then I just added the App/index.js file.

**Comment by jstheoriginal** [comment]
+1 on removing `flex: 1` from the child view inside Collapsible.View.

This one threw me for a loop for hours.

**Comment by iRoachie** [comment]
Closing this by the solution of removing `flex: 1`. If this didn't work and the issue persists then ping me to reopen or create a new issue.
